alter table public.meeting_notes drop constraint if exists meeting_notes_source_check;

alter table public.meeting_notes add constraint meeting_notes_source_check
  check (source in ('T1', 'T2', 'T3', 'T4', 'T5', 'T6', 'T7', 'T8', 'WA', 'NO', 'MAN'));

delete from public.meeting_notes
where source in ('T1', 'T2', 'T3', 'T4', 'T5', 'T6', 'T7', 'T8', 'WA');

insert into public.meeting_notes (title, content, date, category, source, sort_order) values

-- T1 - 26 Subat / Burak UBT
('T1-01', 'Turkish diaspora bilgisi WhatsApp gruplarina dagilmis durumda; tekrar eden sorular ve dusuk kaliteli networking ana problem olarak tanimlandi.', '26 Şubat', 'topluluk-yonetimi', 'T1', 10),
('T1-02', 'Güvenilir doktor, avukat ve danışman bulma eksikliği dolandırıcılık riskini artırıyor; ABD''deki $150K gayrimenkul dolandırıcılığı örnek vaka olarak not edildi.', '26 Şubat', 'audit-kayitlari', 'T1', 11),
('T1-03', 'Cortex, verified expert marketplace, AI twin danışmanlıkları ve merkezi etkinlik yönetimi olan global diaspora platformu olarak konumlandı.', '26 Şubat', 'mvp-hedefleri', 'T1', 12),
('T1-04', 'AI Twins modeliyle uzmanların 7/24 ücretli mini danışmanlık verebilmesi hedeflendi; örnek paket 20 dakika için 50 EUR olarak konuşuldu.', '26 Şubat', 'mvp-hedefleri', 'T1', 13),
('T1-05', 'WhatsApp ve Telegram gruplarındaki bilgileri platforma taşıyacak botlar community integration katmanı olarak planlandı.', '26 Şubat', 'veritabani-tasarimi', 'T1', 14),
('T1-06', 'Barış''ın Almanya 101 girişimi ile Burak''ın Cortex vizyonu global-lokal partnerlik modeli altında hizalanabilir bulundu.', '26 Şubat', 'topluluk-yonetimi', 'T1', 15),
('T1-07', 'Barış Almanya pazar implementasyonunda lokal liderlik rolü için doğal aday olarak değerlendirildi.', '26 Şubat', 'ekip-ve-isbirligi', 'T1', 16),
('T1-08', 'Cortex MVP için 6-8 aylık maraton takvimi ve haftalık 1 saatlik Perşembe toplantısı ritmi benimsendi.', '26 Şubat', 'kullanici-kisitlamalari', 'T1', 17),
('T1-09', 'Barış platform konseptini tek sayfalık özet haline getirecek.', '26 Şubat', 'mvp-hedefleri', 'T1', 18),
('T1-10', 'Barış projeyi Alman politikacı ağı bulunan partneri Fuat ile görüşecek.', '26 Şubat', 'ekip-ve-isbirligi', 'T1', 19),

-- T2 - 12 Mart / Burak UBT
('T2-01', 'Cortex ismi Turkish Atlas yerine evrensel ve yatırımcıya daha uygun marka olarak seçildi.', '12 Mart', 'mvp-hedefleri', 'T2', 30),
('T2-02', 'Cortex, Qualtron Sinclair çatısı altında startup portföyü ve network gücüyle konumlanacak.', '12 Mart', 'ekip-ve-isbirligi', 'T2', 31),
('T2-03', 'AI destekli 50+ soru yöntemiyle iki bağımsız MVP dokümanı hazırlanıp 19 Mart''ta birleştirilecek.', '12 Mart', 'veritabani-tasarimi', 'T2', 32),
('T2-04', 'UI/UX tarafında generic AI görünümü yerine organik, insan unsurları ve Türk motifleri içeren özgün tasarım dili hedeflendi.', '12 Mart', 'mvp-hedefleri', 'T2', 33),
('T2-05', 'Danışmanlar için profesyonel profil, AI Twin chatbot ve ücretli etkinlik yönetimi temel ürün paketi olarak tanımlandı.', '12 Mart', 'mvp-hedefleri', 'T2', 34),
('T2-06', 'Dernekler, STK''lar, okullar ve konsolosluklar için üyelik, bağış ve etkinlik yönetimi modülleri değerlendirildi.', '12 Mart', 'reklam-modeli', 'T2', 35),
('T2-07', 'İşletmeler için directory, premium iş ilanı, indirim kuponu revenue share ve franchise/partnerlik ilanları gelir kalemleri olarak belirlendi.', '12 Mart', 'reklam-modeli', 'T2', 36),
('T2-08', 'WhatsApp/Telegram grup dizini ve onaylı gruplara sponsorlu içerik gönderen bot modeli büyüme ve gelir kanalı olarak not edildi.', '12 Mart', 'topluluk-yonetimi', 'T2', 37),
('T2-09', 'Event takvimi, featured event ve haritada öne çıkan pin özellikleri monetization seçenekleri olarak tanımlandı.', '12 Mart', 'reklam-modeli', 'T2', 38),
('T2-10', 'Dubai Turkish Business Council gibi 2000+ işletmeli diaspora konseyleri toplu onboarding için ilk traction kaynakları olarak görüldü.', '12 Mart', 'reklam-modeli', 'T2', 39),
('T2-11', 'Diaspora influencer ortaklıkları ve Ottogether büyüme modeli kullanıcı kazanımı için referans alındı.', '12 Mart', 'influencer-partnerlikleri', 'T2', 40),
('T2-12', 'Burak startup business modeli, pre-seed, seed, cap table ve onepager standartlarını araştıracak.', '12 Mart', 'audit-kayitlari', 'T2', 41),
('T2-13', 'Barış mevcut MVP dokümanını geliştirecek; iki doküman ve Lovable proje çıktısı 19 Mart toplantısına hazırlanacak.', '12 Mart', 'kullanici-kisitlamalari', 'T2', 42),

-- T3 - 9 Nisan / Burak UBT
('T3-01', 'D.Cortex dashboard tüm notlar, kişiler, dokümanlar ve MVP planı için tek doğruluk kaynağı olacak.', '9 Nisan', 'veritabani-tasarimi', 'T3', 60),
('T3-02', 'WhatsApp, Notion ve Drive arasında dağılan bilgi teknoloji spagettisi problemi olarak tanımlandı.', '9 Nisan', 'veritabani-tasarimi', 'T3', 61),
('T3-03', 'Burak ana Lovable dosyasında vizyonu geniş tutacak; Umut MVP dışı özellikleri backend ve versiyonlama tarafında yönetecek.', '9 Nisan', 'veritabani-tasarimi', 'T3', 62),
('T3-04', 'City Partner modeliyle küçük influencerlara Cortex trafiği ve platform altyapısı karşılığında içerik ve yerel bilgi katkısı önerilecek.', '9 Nisan', 'influencer-partnerlikleri', 'T3', 63),
('T3-05', 'İçerik kaynakları WhatsApp grupları, YouTube, Instagram ve TikTok olarak belirlendi.', '9 Nisan', 'reklam-modeli', 'T3', 64),
('T3-06', 'V2/V3 vizyonunda influencer içeriklerinden otomatik seyahat rotası ve şehir rehberi üreticisi oluşturulması hedeflendi.', '9 Nisan', 'mvp-hedefleri', 'T3', 65),
('T3-07', 'Viral diaspora videolarının yorumlarına manuel Cortex linki bırakma gerilla pazarlama taktiği olarak benimsendi.', '9 Nisan', 'reklam-modeli', 'T3', 66),
('T3-08', 'Gerilla pazarlama operasyonu diaspora gönüllüleri veya stajyerlerle ölçeklenecek.', '9 Nisan', 'ekip-ve-isbirligi', 'T3', 67),
('T3-09', 'Cortex.net Google Console''a eklenecek ve Burak''ın 11+ domaininden backlink verilecek.', '9 Nisan', 'reklam-modeli', 'T3', 68),
('T3-10', 'Seren Uzluer full-time equity bazlı marketing lead adayı olarak değerlendirildi.', '9 Nisan', 'ekip-ve-isbirligi', 'T3', 69),
('T3-11', 'Yeni ekip üyelerine equity ve deferred compensation modelini anlatan SOP dokümanı onboarding materyali olarak kullanılacak.', '9 Nisan', 'kullanici-kisitlamalari', 'T3', 70),
('T3-12', 'Tool matrix hazırlanarak abonelikler, maliyetler ve shared/individual lisans ihtiyacı merkezi takip edilecek.', '9 Nisan', 'audit-kayitlari', 'T3', 71),
('T3-13', 'Founder iletişimi, dokümantasyon ve karar süreçlerini otomatikleştirecek AI Twin vizyonu paralel ürün hattı olarak not edildi.', '9 Nisan', 'mvp-hedefleri', 'T3', 72),
('T3-14', 'Umut D.Cortex dashboard''u 12 Nisan''a kadar finalize edip paylaşacak.', '9 Nisan', 'kullanici-kisitlamalari', 'T3', 73),

-- T4 - 17 Nisan / Burak UBT
('T4-01', 'Yeni proje dashboard''u canlıya alındı ve Notion yerine planlama, araştırma ve dokümantasyonun tek merkezi olarak konumlandı.', '17 Nisan', 'veritabani-tasarimi', 'T4', 90),
('T4-02', 'Dashboard içeriği Danışmanlar, ARGE ve MVP 1/2/3 kolonlarıyla organize edilecek; MVP kolonları pre-launch milestone yapısını temsil edecek.', '17 Nisan', 'veritabani-tasarimi', 'T4', 91),
('T4-03', 'Dashboard başlangıçta manuel kürasyonla kalite kontrollü ilerleyecek, sonra Fathom linkleri AI ile özetlenip kategorize edilecek.', '17 Nisan', 'veritabani-tasarimi', 'T4', 92),
('T4-04', 'Dashboard yatırımcılar için şeffaf bir data room olarak kullanılacak.', '17 Nisan', 'audit-kayitlari', 'T4', 93),
('T4-05', 'Yeni hiring metodolojisi Cihan''ın Head of Growth & Content adaylığı üzerinden test edilecek.', '17 Nisan', 'ekip-ve-isbirligi', 'T4', 94),
('T4-06', 'Hiring süreci iki adım olacak: her kurucu adayla ayrı 30 dakika görüşecek, sonra kurucular sync olup ortak karar verecek.', '17 Nisan', 'kullanici-kisitlamalari', 'T4', 95),
('T4-07', 'Senior core team rollerinde deferred salary, 4 yıllık vesting, 1 yıl cliff ve 2-3% equity bandı kullanılacak.', '17 Nisan', 'audit-kayitlari', 'T4', 96),
('T4-08', 'İkincil ekip için saatlik ödeme veya şirket revenue üretince ödenecek deferred pay modeli değerlendirilecek.', '17 Nisan', 'audit-kayitlari', 'T4', 97),
('T4-09', 'Uluslararası payroll ve compliance yükünü sadeleştirmek için umbrella company modeli araştırılacak.', '17 Nisan', 'kullanici-kisitlamalari', 'T4', 98),
('T4-10', 'WhatsApp bot retention için çekirdek araç ve ileride ayrı ürün hattına dönüşebilecek stratejik katman olarak konumlandı.', '17 Nisan', 'mvp-hedefleri', 'T4', 99),
('T4-11', 'Botun uygulama açmadan WhatsApp içinden visa consultant gibi sorgulara profil listesi döndürmesi hedefleniyor.', '17 Nisan', 'mvp-hedefleri', 'T4', 100),
('T4-12', 'Ambassador, Danışman ve Son Kullanıcı gruplarını organize eden yapısal WhatsApp matrix kurulacak.', '17 Nisan', 'topluluk-yonetimi', 'T4', 101),
('T4-13', 'Umut Cihan görüşmesini yapacak, WhatsApp matrix oluşturacak, dashboard yapısını finalize edecek ve Drive linklerini taşımaya başlayacak.', '17 Nisan', 'ekip-ve-isbirligi', 'T4', 102),
('T4-14', 'Burak compensation matrix''i tamamlayacak, örnek offer letter hazırlayacak ve WhatsApp bot prompt''unu review için paylaşacak.', '17 Nisan', 'ekip-ve-isbirligi', 'T4', 103),
('T4-15', 'Hiring metodolojisi ve örnek offer letter 8 Mayıs 2026''ya kadar finalize edilecek.', '17 Nisan', 'kullanici-kisitlamalari', 'T4', 104),

-- T5 - 20 Nisan / Tahsin oncesi
('T5-01', 'Influencer stratejisinde Ambassador, Partner ve Country Agent kariyer yolu kurgulandı.', '20 Nisan', 'influencer-partnerlikleri', 'T5', 120),
('T5-02', 'Influencerlara topluluk aboneliklerinden recurring revenue sağlayan sürdürülebilir gelir modeli önerilecek.', '20 Nisan', 'reklam-modeli', 'T5', 121),
('T5-03', 'Barış görüşmesinde önce ihtiyacı dinleme, sonra Cortex''i işini büyüteceği platform olarak konumlandırma yaklaşımı benimsendi.', '20 Nisan', 'influencer-partnerlikleri', 'T5', 122),
('T5-04', 'Barış profilinde yüksek enerji ve hızlı aksiyon avantaj; sabırsızlık ve dağılma riski not edildi.', '20 Nisan', 'influencer-partnerlikleri', 'T5', 123),
('T5-05', 'WhatsApp bot MVP''si canlı; onboarding ve SSS cevaplama için kullanılacak.', '20 Nisan', 'mvp-hedefleri', 'T5', 124),
('T5-06', 'Proje dokümantasyonu Q&A formatına çevrilerek bot için yapılandırılmış bilgi tabanı oluşturuldu.', '20 Nisan', 'veritabani-tasarimi', 'T5', 125),
('T5-07', 'WhatsApp botunun 60 günlük ücretsiz deneme sonrası mesaj maliyeti bütçe riski olarak değerlendirilecek.', '20 Nisan', 'audit-kayitlari', 'T5', 126),
('T5-08', 'Spindora AI, Batuhan ile pazarlama partnerliği üzerinden SEO/GEO aracı olarak kullanılacak.', '20 Nisan', 'reklam-modeli', 'T5', 127),
('T5-09', 'MVP onboarding akışında tek ekranda tek soru mantığıyla tinder-style form deneyimi planlandı.', '20 Nisan', 'mvp-hedefleri', 'T5', 128),
('T5-10', 'Atınç Akçayöz için QS senior technical advisor rolü ve formal teklif hazırlığı gündeme alındı.', '20 Nisan', 'ekip-ve-isbirligi', 'T5', 129),
('T5-11', 'Sertaç Yay ile Almanya ambassador veya partnerlik ihtimali için görüşme başlatılacak.', '20 Nisan', 'influencer-partnerlikleri', 'T5', 130),
('T5-12', 'Dashboard içinde tüm proje araçlarını takip edecek Studio bölümü ihtiyacı not edildi.', '20 Nisan', 'veritabani-tasarimi', 'T5', 131),

-- T6 - 20 Nisan / Tahsin
('T6-01', 'Tahsin ile Cortex arasında diaspora topluluk projeleri için olası partnerlik değerlendirildi.', '20 Nisan', 'influencer-partnerlikleri', 'T6', 150),
('T6-02', 'Tahsin''e Sydney gibi bir bölge için Cortex City Partner rolü önerildi.', '20 Nisan', 'influencer-partnerlikleri', 'T6', 151),
('T6-03', 'City Partner modeli Ambassador, City/Country Partner ve Agency Owner kariyer yolu olarak anlatıldı.', '20 Nisan', 'influencer-partnerlikleri', 'T6', 152),
('T6-04', 'Tahsin için revenue share modeli kullanıcı harcamasından %6-10 pay olarak çerçevelendi.', '20 Nisan', 'reklam-modeli', 'T6', 153),
('T6-05', 'Partnerlerin etkinlik, tur ve büyük organizasyonlardan event-based income üretebileceği anlatıldı.', '20 Nisan', 'reklam-modeli', 'T6', 154),
('T6-06', 'Tahsin kendi platformunda diaspora profesyonellerine sosyal medya pazarlaması öğretmeyi planlıyor.', '20 Nisan', 'influencer-partnerlikleri', 'T6', 155),
('T6-07', 'Tahsin''in platformu ücretsiz Instagram temelleri ve ücretli YouTube masterclass katmanlarıyla kurgulanıyor.', '20 Nisan', 'reklam-modeli', 'T6', 156),
('T6-08', 'Tahsin''in uygulaması performans testinde; lansman webinarı yaklaşık iki hafta içinde yapılacak.', '20 Nisan', 'mvp-hedefleri', 'T6', 157),
('T6-09', 'Cortex global diaspora ekosistemi olarak directory, AI matching ve relocation engine avantajlarıyla konumlandırıldı.', '20 Nisan', 'mvp-hedefleri', 'T6', 158),
('T6-10', 'Cortex''in GCC konumu yatırım ve devlet ilgisi açısından stratejik avantaj olarak anlatıldı.', '20 Nisan', 'reklam-modeli', 'T6', 159),
('T6-11', 'Tahsin Cortex teklifini kendi webinarından sonra değerlendirecek.', '20 Nisan', 'influencer-partnerlikleri', 'T6', 160),
('T6-12', 'Taraflar iki hafta sonra Tahsin''in kararını görüşmek üzere tekrar temas kuracak.', '20 Nisan', 'kullanici-kisitlamalari', 'T6', 161),

-- T7 - 20 Nisan / Tahsin sonrasi ve Cihan
('T7-01', 'Cihan, Cortex core marketing rolü için güçlü aday olarak değerlendirildi.', '20 Nisan', 'ekip-ve-isbirligi', 'T7', 180),
('T7-02', 'Cihan''ın BMW, Coca-Cola, Unilever/SAP ve büyük markalarla 15+ yıllık deneyimi stratejik değer olarak not edildi.', '20 Nisan', 'ekip-ve-isbirligi', 'T7', 181),
('T7-03', 'Cortex marketing rolü Content, Influencer Management ve Growth olmak üzere üç ana kolu yönetecek.', '20 Nisan', 'ekip-ve-isbirligi', 'T7', 182),
('T7-04', 'Cihan''ın temel katkısı takipçi sayısından çok kitle uyumu ve kaliteye dayalı influencer seçimi olarak tanımlandı.', '20 Nisan', 'influencer-partnerlikleri', 'T7', 183),
('T7-05', 'French Oje örneği, doğru kitleye sahip micro influencerın büyük hesaplardan daha etkili olabileceğini gösteren referans olarak kullanıldı.', '20 Nisan', 'influencer-partnerlikleri', 'T7', 184),
('T7-06', 'Cihan''ın uzun vadeli topluluk bağlılığı ve riskleri önceden görme yaklaşımı Cortex için değerli bulundu.', '20 Nisan', 'topluluk-yonetimi', 'T7', 185),
('T7-07', 'Cihan için rol co-founder/equity opportunity olarak çerçevelenecek.', '20 Nisan', 'ekip-ve-isbirligi', 'T7', 186),
('T7-08', 'Cihan için maaş + hisse hibrit modeli, maaşın ilk yatırıma kadar ertelenmesi seçeneğiyle değerlendirilecek.', '20 Nisan', 'audit-kayitlari', 'T7', 187),
('T7-09', 'Cihan''a formal offer hazırlanacak ve rol kapsamı yeniden görüşülecek.', '20 Nisan', 'ekip-ve-isbirligi', 'T7', 188),
('T7-10', 'Cihan''ın finansal güvenlik ihtiyacı teklif yapısında dikkate alınacak risk olarak not edildi.', '20 Nisan', 'audit-kayitlari', 'T7', 189),

-- T8 - 24 Nisan / Cihan Burak UBT
('T8-01', '24 Nisan toplantısının amacı Cortex büyümesini hızlandıracak influencer stratejisini finalize etmek olarak belirlendi.', '24 Nisan', 'influencer-partnerlikleri', 'T8', 210),
('T8-02', 'Cihan influencer outreach liderliğini üstlenecek ve ilk temas için Burak Cem''i kullanacak.', '24 Nisan', 'influencer-partnerlikleri', 'T8', 211),
('T8-03', 'İlk hedef 3-5 kilit influencer partneri kazanmak olarak belirlendi.', '24 Nisan', 'influencer-partnerlikleri', 'T8', 212),
('T8-04', 'Tahsin Barış''ın 1.2K üyeli WhatsApp grubu Cortex için competitor acquisition ve community merge fırsatı olarak değerlendirildi.', '24 Nisan', 'topluluk-yonetimi', 'T8', 213),
('T8-05', 'Tahsin Barış''a referral code ve revenue share teklif edilerek topluluğunun organik olarak platforma kayması win-win modele çevrilecek.', '24 Nisan', 'reklam-modeli', 'T8', 214),
('T8-06', 'Influencer value proposition için 5 yıllık revenue share modeli ve welcome package teşviklerini anlatan formal playbook hazırlanacak.', '24 Nisan', 'influencer-partnerlikleri', 'T8', 215),
('T8-07', 'Revenue share örneği olarak refer edilen business subscription gelirlerinden %10 pay modeli konuşuldu.', '24 Nisan', 'reklam-modeli', 'T8', 216),
('T8-08', 'Küçük influencerlar için branded merch ve software trial gibi fiziksel/dijital welcome package teşvikleri kullanılacak.', '24 Nisan', 'influencer-partnerlikleri', 'T8', 217),
('T8-09', 'Pre-launch traction pozitif; ilk günde yaklaşık 20 signup ve üç günde yaklaşık 250 site ziyaretçisi görüldü.', '24 Nisan', 'audit-kayitlari', 'T8', 218),
('T8-10', 'İlk sosyal güven hedefi 8K-10K follower seviyesine ulaşıp hareket algısı yaratmak olarak belirlendi.', '24 Nisan', 'reklam-modeli', 'T8', 219),
('T8-11', 'Influencer hedef profili 50K-150K takipçili, özellikle HR/career ve YouTube ağırlıklı hesaplar olarak tanımlandı.', '24 Nisan', 'influencer-partnerlikleri', 'T8', 220),
('T8-12', 'Burak Cem''in 146K takipçisi ve yeni nesil göçmen kitlesi Cortex için güçlü ilk hedef olarak değerlendirildi.', '24 Nisan', 'influencer-partnerlikleri', 'T8', 221),
('T8-13', 'Blog contest ile diaspora deneyimine dair mizahi, duygusal ve pratik hikayeler toplanacak.', '24 Nisan', 'reklam-modeli', 'T8', 222),
('T8-14', 'Blog yarışması için $1K-$3K ödül havuzu trafik ve kaliteli UGC üretimi için kullanılacak.', '24 Nisan', 'audit-kayitlari', 'T8', 223),
('T8-15', 'Stories referral linkleri için ana kanal, postlar ayrı bütçe gerektiren format, YouTube ise yüksek etkili sponsorlu video kanalı olarak ayrıldı.', '24 Nisan', 'reklam-modeli', 'T8', 224),
('T8-16', 'Keyword-triggered DM automation ile referral linklerinin influencer kitlesine otomatik iletilmesi planlandı.', '24 Nisan', 'mvp-hedefleri', 'T8', 225),
('T8-17', 'Cihan Burak Cem''den influencer value proposition hakkında ilk feedback alacak ve 3-4 potansiyel partner daha belirleyecek.', '24 Nisan', 'ekip-ve-isbirligi', 'T8', 226),
('T8-18', 'Qualtron ve Umut influencer playbook ile landing page için prototype influencer dashboard hazırlayacak.', '24 Nisan', 'ekip-ve-isbirligi', 'T8', 227),
('T8-19', 'Playbook ve Cihan bulgularını değerlendirmek için sonraki hafta follow-up toplantısı yapılacak.', '24 Nisan', 'kullanici-kisitlamalari', 'T8', 228),

-- WA - 13-24 Nisan WhatsApp
('WA-01', 'LinkedIn üzerinden ilk tanışma sonrası Qatar-Dubai bağlantısı ve CorteQS grup davet linki paylaşıldı.', '13 Nisan WA', 'ekip-ve-isbirligi', 'WA', 300),
('WA-02', 'payaltr.com ve qualtronsinclair.com üzerinden CORTEX-TURK ana hub fikri şekillendi.', '13 Nisan WA', 'mvp-hedefleri', 'WA', 301),
('WA-03', 'Turqua-z.com, CorteQS ve alternatif isimler için data ile karar verme ve marka oylama yaklaşımı konuşuldu.', '13 Nisan WA', 'mvp-hedefleri', 'WA', 302),
('WA-04', 'UBT''ye CTO rolü açıkça teklif edildi.', '13 Nisan WA', 'ekip-ve-isbirligi', 'WA', 303),
('WA-05', 'corteqs.net domaini ve TurkAtlas, TurkHub, TurkSphere gibi isim alternatifleri tartışıldı.', '13 Nisan WA', 'mvp-hedefleri', 'WA', 304),
('WA-06', 'Haftalık Perşembe Zoom serisi 12:30 Qatar ve 14:30 Almanya saatiyle 108 occurrence olarak başlatıldı.', '13 Nisan WA', 'kullanici-kisitlamalari', 'WA', 305),
('WA-07', 'Lovable workspace admin erişimi, repo GitHub push ve sandbox/merge stratejisi netleştirildi.', '13 Nisan WA', 'veritabani-tasarimi', 'WA', 306),
('WA-08', 'Blog yazısı planı, Relocation Engine fikri ve danışman/yazar kategorisi önerisi gündeme geldi.', '13 Nisan WA', 'reklam-modeli', 'WA', 307),
('WA-09', 'Akın Özkan için iş yerleştirme ve Kemal Hakimoğlu referansı network aksiyonu olarak not edildi.', '13 Nisan WA', 'topluluk-yonetimi', 'WA', 308),
('WA-10', 'delphi.ai ve RAG yaklaşımı incelenerek danışman twin fikri güçlendirildi.', '13 Nisan WA', 'mvp-hedefleri', 'WA', 309),
('WA-11', 'cordocu.vercel.app yeni üyenin projeyi hızlı anlayacağı dashboard olarak paylaşıldı.', '13 Nisan WA', 'veritabani-tasarimi', 'WA', 310),
('WA-12', 'Tech lead adayı muted observer olarak toplantıya davet edildi.', '13 Nisan WA', 'ekip-ve-isbirligi', 'WA', 311),
('WA-13', 'Cap table modelleri ve önce gönül verecek 10 kişi, sonra para prensibi gündeme geldi.', '13 Nisan WA', 'audit-kayitlari', 'WA', 312),
('WA-14', 'Ortak Instagram collection ve danışman/ambassador profil havuzu oluşturulacak.', '13 Nisan WA', 'influencer-partnerlikleri', 'WA', 313),
('WA-15', 'corteqs.net alındı; corteqs.co ve corteqs.ai domainleri sonraki adım olarak planlandı.', '13 Nisan WA', 'mvp-hedefleri', 'WA', 314),
('WA-16', 'Landing page için ülke kayıt sayaçları, şehir elçisi başvuru sayfası ve teaser video düşünüldü.', '13 Nisan WA', 'reklam-modeli', 'WA', 315),
('WA-17', 'Crowdfund açılışı için aynı landing page''in kullanılması fikri not edildi.', '13 Nisan WA', 'audit-kayitlari', 'WA', 316),
('WA-18', 'Subdomain mimarisinde Burak Lovable ve CorDocu ayrı subdomain olarak konumlanacak.', '13 Nisan WA', 'veritabani-tasarimi', 'WA', 317),
('WA-19', 'Pilot ülkeler Qatar, Almanya ve UAE ekseninde tartışıldı; T modelle derinleşme ve paralel ambassador arama başlatılacak.', '17 Nisan WA', 'reklam-modeli', 'WA', 330),
('WA-20', 'AR-GE dosyaları dashboard''da kritik bilgilerin sürekli güncellendiği ayrı klasör olarak tutulacak.', '17 Nisan WA', 'veritabani-tasarimi', 'WA', 331),
('WA-21', 'İK klasörü CV, görev tanımı ve teklif dosyalarını merkezi tutmak için açılacak.', '17 Nisan WA', 'ekip-ve-isbirligi', 'WA', 332),
('WA-22', 'Bot yazışmaları ve dokümanları sınıflandırıp admin panele aktaracak şekilde entegre edilecek.', '17 Nisan WA', 'veritabani-tasarimi', 'WA', 333),
('WA-23', 'Sosyal Medya İçerik Yöneticisi rolü ihtiyacı tanımlandı.', '17 Nisan WA', 'ekip-ve-isbirligi', 'WA', 334),
('WA-24', 'Cihan Akıncı için tanışma videosu paylaşıldı, teklif konuşması ve Drive teklif metinleri gündeme geldi.', '17 Nisan WA', 'ekip-ve-isbirligi', 'WA', 335),
('WA-25', 'Ticaret Bakanlığı yurt dışı teşkilatı ülke ve pazar bilgileri veri kaynağı olarak not edildi.', '17 Nisan WA', 'reklam-modeli', 'WA', 336),
('WA-26', 'LinkedIn ve Instagram açıldı; Facebook açılacak, TikTok kararı beklemede bırakıldı.', '17 Nisan WA', 'reklam-modeli', 'WA', 337),
('WA-27', 'LinkedIn Company Page oluşturuldu, admin erişimleri atandı ve arka plan format sorunu çözülecek.', '17 Nisan WA', 'reklam-modeli', 'WA', 338),
('WA-28', 'Instagram hesabı dashboard''a entegre edildi; sosyal medya şifreleri güvenlik kontrolünden sonra eklenecek.', '17 Nisan WA', 'veritabani-tasarimi', 'WA', 339),
('WA-29', 'İnsan kaynakları sayfası çalışır hale getirildi; toplantı notları, WA konuşmaları ve Notion tek sayfada toplandı.', '17 Nisan WA', 'veritabani-tasarimi', 'WA', 340),
('WA-30', 'Todo listesinin iş büyüdükçe disiplinli kullanılması zorunlu görüldü.', '17 Nisan WA', 'kullanici-kisitlamalari', 'WA', 341),
('WA-31', 'Landing page database kontrolü ve launch planı öncelikli ana sayfa işi olarak belirlendi.', '17 Nisan WA', 'mvp-hedefleri', 'WA', 342),
('WA-32', 'Vlogger verilerini tool''lara entegre etme fikri araştırılacak.', '17 Nisan WA', 'mvp-hedefleri', 'WA', 343),
('WA-33', 'Seren Uzluer Taplak için full social media launch paketi ve düzenli içerik planı teklifi değerlendirildi.', '17 Nisan WA', 'reklam-modeli', 'WA', 344),
('WA-34', 'RASCI modeli oluşturularak sorumluluklar netleştirilecek.', '17 Nisan WA', 'kullanici-kisitlamalari', 'WA', 345),
('WA-35', 'Tech Cost Fizibilite Matrisi hazırlanacak.', '17 Nisan WA', 'audit-kayitlari', 'WA', 346),
('WA-36', 'CorteQS WhatsApp yapısı Mastermind Bot, Admin Bot, Role Based Bot ve Kanal Bot katmanlarıyla kurulacak.', '17 Nisan WA', 'mvp-hedefleri', 'WA', 347),
('WA-37', 'LinkedIn Company Page''de iş ilanlarından önce follower kazanımına odaklanılacak.', '17 Nisan WA', 'reklam-modeli', 'WA', 348),
('WA-38', 'Barış Avustralya community''si için erken temas ve win-win strateji kurulması gündeme geldi.', '18 Nisan WA', 'influencer-partnerlikleri', 'WA', 360),
('WA-39', 'CorteQS WhatsApp community linki landing page''e eklenecek ve kullanıcılar buradan yönlendirilecek.', '18 Nisan WA', 'topluluk-yonetimi', 'WA', 361),
('WA-40', 'WhatsApp botu hoş geldin akışına konumlandırılarak yeni gelenlere kısa sürede bilgi verecek.', '18 Nisan WA', 'mvp-hedefleri', 'WA', 362),
('WA-41', 'Landing SEO/GEO ayarları için SSS ve yapısal içerikler zorunlu hale geldi.', '18 Nisan WA', 'reklam-modeli', 'WA', 363),
('WA-42', 'Influencerlar gelmeden önce aday database''i oluşturma ve açıklamalarla doldurma ihtiyacı gündeme geldi.', '20 Nisan WA', 'influencer-partnerlikleri', 'WA', 380),
('WA-43', 'Landing launch sonrasında kurucular LinkedIn pozisyonlarını görünür hale getirecek.', '20 Nisan WA', 'reklam-modeli', 'WA', 381),
('WA-44', 'Harici görüşmelerden önce adaylara iddialı ama ölçülü bir onepager gönderme kuralı önerildi.', '20 Nisan WA', 'ekip-ve-isbirligi', 'WA', 382),
('WA-45', 'Referral programının hızlıca hayata geçirilmesi gerektiği ve ödeme altyapısı seçeneklerinin araştırılacağı konuşuldu.', '20 Nisan WA', 'audit-kayitlari', 'WA', 383),
('WA-46', 'Bot, landing page ve topluluk hazırlıkları tamamlanarak Cihan''ın hafta içinde içeri alınması hedeflendi.', '21 Nisan WA', 'ekip-ve-isbirligi', 'WA', 400),
('WA-47', 'Sosyal medya çağrıları ve LinkedIn dağıtımı launch öncesi yumuşak büyüme kanalı olarak kullanılacak.', '21 Nisan WA', 'reklam-modeli', 'WA', 401),
('WA-48', 'Influencer seçiminde takipçi sayısından çok akıllı seçim ve kitle kalitesi önceliklendirilecek.', '21 Nisan WA', 'influencer-partnerlikleri', 'WA', 402),
('WA-49', 'Landing AI/bot akışı ile klasik formun aynı sayfada birlikte sunulması uygun görüldü.', '21 Nisan WA', 'mvp-hedefleri', 'WA', 403),
('WA-50', 'HR takipçileri güçlü olduğu için yurt dışındaki HR profilleri ikinci influencer kanalı olarak görüldü.', '21 Nisan WA', 'influencer-partnerlikleri', 'WA', 404),
('WA-51', 'Community duyurusunda topluluk sahiplerine gelir ortaklığı ve topluluğunu koruma mesajı öne çıkarılacak.', '23 Nisan WA', 'topluluk-yonetimi', 'WA', 420),
('WA-52', 'Yeni WhatsApp grup yapısı core topluluktan ayrı ve kontrollü davet kanalı olarak kurgulanacak.', '23 Nisan WA', 'topluluk-yonetimi', 'WA', 421),
('WA-53', 'Katılacak topluluk liderleri için referral gönderme ve davet akışını izleme ihtiyacı not edildi.', '23 Nisan WA', 'audit-kayitlari', 'WA', 422),
('WA-54', 'Cihan topluluğa dahil edildi ve erken core hareketin parçası haline geldi.', '23 Nisan WA', 'ekip-ve-isbirligi', 'WA', 423),
('WA-55', 'Topluluk liderleri için güvenlik, hukuk ve ana WhatsApp yapısı ayrı çalışma başlıkları olarak ayrıldı.', '23 Nisan WA', 'topluluk-yonetimi', 'WA', 424),
('WA-56', 'Seren''in topluluk liderleri kanalına alınıp content üretimi ve bağlam artırma sorumluluğu alması önerildi.', '23 Nisan WA', 'ekip-ve-isbirligi', 'WA', 425),
('WA-57', 'Influencer management için international-national co-manager düzeniyle tek kişi riskini azaltma fikri gündeme geldi.', '23 Nisan WA', 'influencer-partnerlikleri', 'WA', 426),
('WA-58', 'Instagram DM mesajları CorteQS hesabından atılacak şekilde influencer outreach taktiği netleştirilecek.', '23 Nisan WA', 'influencer-partnerlikleri', 'WA', 427),
('WA-59', 'Reddit r/diasporaturks kanalı otomasyon ve dağıtım kanalı olarak değerlendirilecek.', '23 Nisan WA', 'reklam-modeli', 'WA', 428),
('WA-60', 'Community mesajlarında pinli ana mesaj ve kısa güncel teaserlar kullanma yaklaşımı benimsendi.', '24 Nisan WA', 'topluluk-yonetimi', 'WA', 440),
('WA-61', 'Bireysel destek verecek ama danışman olmayan kişiler için Contributors veya Community Contributors adı önerildi.', '24 Nisan WA', 'topluluk-yonetimi', 'WA', 441),
('WA-62', 'LinkedIn postlarının boşa gitmemesi için landing ana sayfada sliding news/admin içerik yapısı kullanılacak.', '24 Nisan WA', 'reklam-modeli', 'WA', 442),
('WA-63', 'Sliding news detay sayfaları LinkedIn postlarına bağlanarak trafik artırma kanalı olarak kullanılacak.', '24 Nisan WA', 'reklam-modeli', 'WA', 443),
('WA-64', 'Barış Avustralya takipçileri CorteQS hesabıyla günlük 100-150 takip stratejisiyle izlenecek.', '24 Nisan WA', 'influencer-partnerlikleri', 'WA', 444),
('WA-65', 'Avustralya için 50 Türk Instagram influencer başlangıç listesi outreach ve scraping havuzu olarak çıkarıldı.', '24 Nisan WA', 'influencer-partnerlikleri', 'WA', 445),
('WA-66', 'Influencer listeleri master arşivde güncel ve erişilebilir tutulacak.', '24 Nisan WA', 'veritabani-tasarimi', 'WA', 446),
('WA-67', 'Influencer CRM''inde kime hangi içerik, davet veya işbirliği gittiği takip edilecek.', '24 Nisan WA', 'veritabani-tasarimi', 'WA', 447),
('WA-68', 'Platform maskotu için teknoloji yönünü vurgulayan ama özelleştirilecek bir görsel fikir todo olarak kaydedilecek.', '24 Nisan WA', 'mvp-hedefleri', 'WA', 448),
('WA-69', 'Katılımcıları hareketlendirmek için bilgi ve anket içeren küçük sayfa fikri toplantı konusu olarak ayrıldı.', '24 Nisan WA', 'topluluk-yonetimi', 'WA', 449);
