ALTER TABLE meeting_notes DROP CONSTRAINT IF EXISTS meeting_notes_source_check;
ALTER TABLE meeting_notes ADD CONSTRAINT meeting_notes_source_check
  CHECK (source IN ('T1', 'T2', 'T3', 'WA', 'NO'));

INSERT INTO meeting_notes (title, content, date, category, source, sort_order) VALUES
('MVP v2.0 doküman takası', '17 Mart''a kadar MVP v2.0 dokümanları karşılıklı gönderilecek.', '17 Mart', 'mvp-hedefleri', 'NO', 100),
('Nihai doküman birleştirme', '19''unda Barış 2 dokümanı + Lovable projesini birleştirip nihai doküman oluşturacak.', '19 Mart', 'mvp-hedefleri', 'NO', 101),
('MVP çıkış hedefi', '2-3 toplantı sonra MVP çıkartılabilir.', '17 Mart', 'mvp-hedefleri', 'NO', 102),
('Startup 0-100 standartları', 'Barak: startup business 0-100 standartlarını incele (tohum → exit, seed, preseed); onepager hazırlanacak.', '17 Mart', 'kullanici-kisitlamalari', 'NO', 103),
('Core Team rolleri', 'Core Team: Burak Akçakanat (iş geliştirme, strateji, network) + Barış UBT (CTO, teknik liderlik).', '17 Mart', 'kullanici-kisitlamalari', 'NO', 104),
('Teknik kumanda UBT', 'Teknik kumanda UBT''de — Burak.', '17 Mart', 'kullanici-kisitlamalari', 'NO', 105),
('Domain bazlı ownership', 'Yönetim tasarımı mantığı: domain bazlı ownership, fonksiyon bazlı değil.', '17 Mart', 'kullanici-kisitlamalari', 'NO', 106),
('WA influencer kanalı', 'WhatsApp grubu influencerlar için ayrı kanal.', '17 Mart', 'reklam-modeli', 'NO', 107),
('SEO blog yarışması', 'SEO için seyahat bloggerları blog yazısı yarışması ile toplanacak.', '17 Mart', 'reklam-modeli', 'NO', 108),
('City Ambassador modeli', 'Blogger/Influencer = City Ambassador modeli.', '17 Mart', 'reklam-modeli', 'NO', 109),
('VIT Jukebox entegrasyonu', 'VIT Jukebox/borsa fikri entegrasyonu.', '17 Mart', 'mvp-hedefleri', 'NO', 110),
('OdtuGather entegrasyonu', 'OdtuGather fikirlerinin entegrasyonu.', '17 Mart', 'mvp-hedefleri', 'NO', 111),
('Vlogger işbirliği', 'Vlogger işbirliği ile traction.', '17 Mart', 'reklam-modeli', 'NO', 112),
('Jukebox ayrı app', 'Jukebox → ileride ayrı app.', '17 Mart', 'mvp-hedefleri', 'NO', 113),
('Ambassador mantığı', 'Ambassador mantığı çalışıldı (Drive dökümanı + Lovable mock).', '17 Mart', 'mvp-hedefleri', 'NO', 114),
('Haberler modülü', 'Haberler mantığı kondu.', '17 Mart', 'mvp-hedefleri', 'NO', 115),
('Hospital booking', 'Hospital booking eklendi.', '17 Mart', 'rezervasyon-sistemi', 'NO', 116),
('Jukebox mevcut', 'Jukebox zaten vardı (ileride işletme müzik sistemleri entegre edilecek).', '17 Mart', 'mvp-hedefleri', 'NO', 117),
('Hizmet talebi formu', 'Bireysel kullanıcı profilinden hizmet talebi açıldı.', '17 Mart', 'mvp-hedefleri', 'NO', 118),
('Admin dashboard başlangıcı', 'Admin dashboard yapılanmaya başladı. Şehir Elçileri mantığı çalışıldı.', '17 Mart', 'mvp-hedefleri', 'NO', 119),
('Tüm işletmeler eklenecek', 'İşletmeler her türlü eklenecek.', '12 Mart', 'reklam-modeli', 'NO', 120),
('Dubai Business Council', 'Dubai Business Council üzerinden 1000-2000 işletme hedefi (Burak tanıyor).', '12 Mart', 'reklam-modeli', 'NO', 121),
('Mass migration veri tabanı', 'Mass migration veri tabanı değerlendirilecek (KVKK kontrolü).', '12 Mart', 'veritabani-tasarimi', 'NO', 122),
('Danışmana danışmanlık ürünü', '''Danışmana danışmanlık'' ürünü: mikrosite + AI twin + chatbot.', '12 Mart', 'reklam-modeli', 'NO', 123),
('Teknik yük değerlendirmesi', 'Teknik yük değerlendirilecek.', '12 Mart', 'veritabani-tasarimi', 'NO', 124),
('Danışman claiming', 'Bireysel danışman: claiming + olanaklar.', '17 Mart', 'reklam-modeli', 'NO', 125),
('Kuruluşlar hedefi', 'Kuruluşlar: konsolosluk, vakıf, dernek.', '17 Mart', 'reklam-modeli', 'NO', 126),
('Bağış/aidat toplama', 'Bağış/aidat toplama.', '17 Mart', 'audit-kayitlari', 'NO', 127),
('Etkinlik yönetim arayüzü', 'Etkinlik yönetim arayüzü.', '17 Mart', 'reklam-modeli', 'NO', 128),
('İşletme indirim çeki', 'İşletme: restoran/market indirim çeki.', '17 Mart', 'reklam-modeli', 'NO', 129),
('İş ilanları', 'İş ilanları: işletme + genel pool.', '17 Mart', 'reklam-modeli', 'NO', 130),
('İş fırsatları ortaklık', 'İş fırsatları ortaklık: yurt dışına açılma.', '17 Mart', 'reklam-modeli', 'NO', 131),
('WA grupları kategorizasyon', 'WA grupları kategorizasyon.', '17 Mart', 'reklam-modeli', 'NO', 132),
('Etkinlik sponsorluk', 'Etkinlikler: filtreleme, featured sponsorluk, harita.', '17 Mart', 'reklam-modeli', 'NO', 133),
('Blogger/Vlogger haberler', 'Blogger/Vlogger, haberler.', '17 Mart', 'reklam-modeli', 'NO', 134),
('Hoşgeldin paketi', 'Hoşgeldin paketi.', '17 Mart', 'reklam-modeli', 'NO', 135),
('Roadmap hedefleri', 'Roadmap: Fikir→İnovasyon → Teknoloji→MVP → Traction→Marketing → Tutundurma→UI/UX → Ölçekleme→Yatırım.', '24 Mart', 'mvp-hedefleri', 'NO', 136),
('Hoşgeldin paketi eklentiler', 'Hoşgeldin paketine eklenenler: uçak bileti discount, araç kiralama, havaalanı transferi — teklif sistemi entegre.', '24 Mart', 'reklam-modeli', 'NO', 137),
('CorteQS WA Kanalı', 'CorteQS WA Kanalı: kullanıcı hem kanala hem bota bağlı.', '24 Mart', 'reklam-modeli', 'NO', 138),
('Etkileşim havuzu sponsorluğu', 'Etkileşim havuzu sponsorluğu (OdtuGather/all2gather özelliği buraya aktarılacak).', '24 Mart', 'reklam-modeli', 'NO', 139),
('Event sponsor management', 'Uzun vade: event sponsor management platform olabilir.', '24 Mart', 'mvp-hedefleri', 'NO', 140),
('6 Domain Ownership', '6 Domain Ownership modeli: Supply, Demand, Transaction, Product, Platform Core, Support & CRM.', '17 Mart', 'veritabani-tasarimi', 'NO', 141),
('Domain owner sorumluluk', 'Her domain = 1 owner prensibi; owner KPI''lardan, backlog''dan, büyümeden sorumlu.', '17 Mart', 'veritabani-tasarimi', 'NO', 142),
('Domain owner mikro yönetim yok', 'Domain owner mikro yönetim yapmaz.', '17 Mart', 'veritabani-tasarimi', 'NO', 143),
('Supply Owner KPI', 'Supply Owner KPI: onboard edilen advisor #, aktif advisor %, partner sayısı.', '17 Mart', 'audit-kayitlari', 'NO', 144),
('Demand Owner KPI', 'Demand Owner KPI: WAU, yeni kullanıcı #, ambassador output, community engagement %.', '17 Mart', 'audit-kayitlari', 'NO', 145),
('Revenue Owner KPI', 'Revenue Owner KPI: GMV, net revenue, take rate %, conversion rate %.', '17 Mart', 'audit-kayitlari', 'NO', 146),
('Operasyon ritüelleri', 'Operasyon: haftalık 10''ar dk owner update + KPI review; aylık retro.', '17 Mart', 'kullanici-kisitlamalari', 'NO', 147),
('GPT sistem analizi', 'GPT prompt ile tam sistem analizi: kullanıcı tipleri, feature gap, gelir modeli, versiyon önceliklendirme (V1/V2/V3).', '17 Mart', 'veritabani-tasarimi', 'NO', 148),
('Product backlog', 'Çıktı: product backlog (feature name, description, priority, dependencies, implementation). 2 Nisan toplantısında konuşuldu.', '2 Nisan', 'veritabani-tasarimi', 'NO', 149),
('Google Drive klasörü', 'Ana Google Drive klasörü ve ilk dokümentasyon taslağı oluşturuldu.', '17 Mart', 'audit-kayitlari', 'NO', 150),
('Cap Table çalışmaları', 'Cap Table v1 + v2 çalışma devam ediyor.', '17 Mart', 'audit-kayitlari', 'NO', 151),
('Referans site incelemesi', 'Referans siteler incelendi: qualtronsinclair.com, diasporanet-connect, tuerkischeaerzte.de, relocate.me.', '17 Mart', 'audit-kayitlari', 'NO', 152);
