-- WA2 — 17 Nisan WA: summary2.txt içindeki son iki #summary arasındaki maddeler
insert into meeting_notes (title, content, date, category, source, sort_order) values

('WA2-01', 'WhatsApp bot mimarisi kararı: resmi (paralı servis) mi yoksa alternatif yöntem mi kullanılacak netleştirilecek.', '17 Nisan WA', 'mvp-hedefleri', 'WA', 200),
('WA2-02', 'Pilot ülkeler önerildi: Qatar ve Almanya; Burak, Qatar yerine UAE''yi tercih etti.', '17 Nisan WA', 'reklam-modeli', 'WA', 201),
('WA2-03', 'Pilot ülkeler stratejisi: T modelle derinleştirme ve paralelde ambassador arama başlatılacak.', '17 Nisan WA', 'reklam-modeli', 'WA', 202),
('WA2-04', 'AR-GE dosyaları klasörü dashboard''da oluşturulacak; kritik bilgiler sürekli güncellenerek tutulacak.', '17 Nisan WA', 'veritabani-tasarimi', 'WA', 203),
('WA2-05', 'İK (HR) klasörü gerekiyor: CV''ler, görev tanımları, teklifler.', '17 Nisan WA', 'kullanici-kisitlamalari', 'WA', 204),
('WA2-06', 'Bot, yazışmaları ve dökümanları sınıflandırıp admin panele aktaracak şekilde entegre edilecek.', '17 Nisan WA', 'veritabani-tasarimi', 'WA', 205),
('WA2-07', 'Sosyal Medya İçerik Yöneticisi rolü ihtiyacı tanımlandı.', '17 Nisan WA', 'reklam-modeli', 'WA', 206),
('WA2-08', 'Dashboard düzenlemeleri devam ediyor: user submission, döküman ve link görünümü iyileştirildi.', '17 Nisan WA', 'veritabani-tasarimi', 'WA', 207),
('WA2-09', 'Cihan Akıncı değerlendirmesi: tanışma videosu paylaşıldı, teklif konuşması yapılacak; Drive''da örnek teklif metinleri mevcut.', '17 Nisan WA', 'kullanici-kisitlamalari', 'WA', 208),
('WA2-10', 'Ticaret Bakanlığı yurt dışı teşkilatı (ticaret.gov.tr) — ülkeler ve pazar bilgileri veri kaynağı.', '17 Nisan WA', 'reklam-modeli', 'WA', 209),
('WA2-11', 'WhatsApp Bot mimarisi ve işe alım metodolojisi 17 Nisan toplantısının ana gündem maddeleri.', '17 Nisan WA', 'mvp-hedefleri', 'WA', 210),
('WA2-12', 'LinkedIn ve Instagram açıldı; Facebook açılacak, TikTok kararı henüz verilmedi.', '17 Nisan WA', 'reklam-modeli', 'WA', 211),
('WA2-13', 'LinkedIn Company Page oluşturuldu, admin erişimleri atandı; arka plan format sorunu çözülecek.', '17 Nisan WA', 'reklam-modeli', 'WA', 212),
('WA2-14', 'Instagram hesabı dashboard''a entegre edildi; sosyal medya şifreleri güvenlik kontrolü sonrası eklenecek.', '17 Nisan WA', 'veritabani-tasarimi', 'WA', 213),
('WA2-15', 'İnsan kaynakları sayfası çalışır hale getirildi; toplantı notları, WA konuşmaları ve Notion tek sayfada toplandı.', '17 Nisan WA', 'veritabani-tasarimi', 'WA', 214),
('WA2-16', 'Todo listesinin etkin kullanım disiplini — iş büyüdükçe todo takibi zorunlu.', '17 Nisan WA', 'veritabani-tasarimi', 'WA', 215),
('WA2-17', 'Ana sayfanın DB bağlantıları yapılacak; öncelik landing page database kontrolü ve launch planı.', '17 Nisan WA', 'veritabani-tasarimi', 'WA', 216),
('WA2-18', 'Vlogger verilerini tool''lara entegre etme fikri araştırılacak.', '17 Nisan WA', 'mvp-hedefleri', 'WA', 217),
('WA2-19', 'Landing page iskelet yapısı ve rijidlik testleri yapılacak.', '17 Nisan WA', 'mvp-hedefleri', 'WA', 218),
('WA2-20', 'Seren Uzluer Taplak: full social media launch paketi + düzenli içerik planı teklifi.', '17 Nisan WA', 'reklam-modeli', 'WA', 219),
('WA2-21', 'Gerilla pazarlama: diaspora içeriklerine Corteqs linki bırakma taktiği.', '17 Nisan WA', 'reklam-modeli', 'WA', 220),
('WA2-22', 'Stajyer / proje destek ekip ihtiyacı gündeme geldi.', '17 Nisan WA', 'kullanici-kisitlamalari', 'WA', 221),
('WA2-23', 'DATA DATA DATA — veri toplama ve strateji birinci öncelik.', '17 Nisan WA', 'veritabani-tasarimi', 'WA', 222),
('WA2-24', 'RASCI modeli oluşturulacak; sorumluluklar netleştirilecek.', '17 Nisan WA', 'kullanici-kisitlamalari', 'WA', 223),
('WA2-25', 'Tech Cost Fizibilite Matrisi hazırlanacak.', '17 Nisan WA', 'audit-kayitlari', 'WA', 224),
('WA2-26', 'Güzel AI prompt çıktılarının linkleri ekip içinde paylaşılacak; paylaşım sistemi kurulacak.', '17 Nisan WA', 'mvp-hedefleri', 'WA', 225),
('WA2-27', 'CorteQS yönetim kullanıcı profili oluşturulacak.', '17 Nisan WA', 'veritabani-tasarimi', 'WA', 226),
('WA2-28', 'Ekip ücret & hisse breakdown analizi yapılacak.', '17 Nisan WA', 'audit-kayitlari', 'WA', 227),
('WA2-29', 'Toplantı ajandası (17 Nisan): MVP iskelet, MVP1, ekip ücret breakdown, iş tanımı ve özlük hakları rolleri.', '17 Nisan WA', 'kullanici-kisitlamalari', 'WA', 228),
('WA2-30', 'İK metodolojisi: beğenilen kişinin pozisyonu ve haftalık saat taahhüdü modeli; Cihan örnek vaka.', '17 Nisan WA', 'kullanici-kisitlamalari', 'WA', 229),
('WA2-31', 'Teklif modeli Circle 1-2-3-4 yapısı tanımlanacak.', '17 Nisan WA', 'kullanici-kisitlamalari', 'WA', 230),
('WA2-32', 'Çalışma modeli seçenekleri: Saatlik / Part-time / Full-time.', '17 Nisan WA', 'kullanici-kisitlamalari', 'WA', 231),
('WA2-33', 'Ödeme modeli: Gecikmeli vs. anlık ödeme seçenekleri netleştirilecek.', '17 Nisan WA', 'audit-kayitlari', 'WA', 232),
('WA2-34', 'Sözleşme son hali veya örneği hazırlanacak; tablolar ve Drive yeni yapıya taşınacak.', '17 Nisan WA', 'kullanici-kisitlamalari', 'WA', 233),
('WA2-35', 'Umbrella company modeli araştırılacak.', '17 Nisan WA', 'kullanici-kisitlamalari', 'WA', 234),
('WA2-36', 'Aday araştırması başlatılıyor: UBT adaylara bakacak; Cihanla görüşme — Burak onay, Barış görüşecek.', '17 Nisan WA', 'kullanici-kisitlamalari', 'WA', 235),
('WA2-37', 'CorteQS WhatsApp yapısı: Mastermind Bot + Admin Bot + Role Based Bot + Kanal Bot.', '17 Nisan WA', 'mvp-hedefleri', 'WA', 236),
('WA2-38', 'LinkedIn Company Page''e önce follower kazanımı odaklanılmalı; iş ilanları sonraki aşamada.', '17 Nisan WA', 'reklam-modeli', 'WA', 237)
on conflict do nothing;
