alter table public.meeting_notes drop constraint if exists meeting_notes_source_check;

alter table public.meeting_notes add constraint meeting_notes_source_check
  check (source in ('T1', 'T2', 'T3', 'T4', 'T5', 'T6', 'T7', 'T8', 'T9', 'WA', 'NO', 'MAN'));

insert into public.meeting_notes (title, content, date, category, source, sort_order) values

-- WA4 - 25-30 Nisan WhatsApp
('WA4-01', 'Referral kodu zorunlu olacak; database tarafında kontrol edilerek çalıştırılacak.', '25 Nisan WA', 'veritabani-tasarimi', 'WA', 580),
('WA4-02', 'Influencer, contributor ve yarışma materyalleri Drive''da hazırlandı; bunlardan dış sunum ve iletişim dokümanları üretilecek.', '25 Nisan WA', 'ekip-ve-isbirligi', 'WA', 581),
('WA4-03', 'İşbirliği davetlerinde video teaser, podcast ve PDF/HTML tanıtım paketi daha ikna edici formatlar olarak değerlendirilecek.', '25 Nisan WA', 'reklam-modeli', 'WA', 582),
('WA4-04', 'Ekip yapısı ve iş ilanları finalize edilince LinkedIn, site ve sosyal medya üzerinden CV toplama açılacak.', '26 Nisan WA', 'ekip-ve-isbirligi', 'WA', 583),
('WA4-05', 'Stajyer rolü için ayrıca iş tanımı hazırlanıp ekip yapısına eklenecek.', '26 Nisan WA', 'ekip-ve-isbirligi', 'WA', 584),
('WA4-06', 'İşletme ve danışman kayıtlarında platform üyelerine özel indirim yüzdesi ve süreli kupon mantığı toplanacak.', '26 Nisan WA', 'mvp-hedefleri', 'WA', 585),
('WA4-07', 'Blogger yarışmasına ek olarak ayrı Vlogger-Influencer yarışması ve ayrı landing page akışı planlandı.', '26 Nisan WA', 'reklam-modeli', 'WA', 586),
('WA4-08', 'Founding 1000 kampanyası ana landing page altında ayrı bir sayfa olarak kurgulanacak.', '26 Nisan WA', 'reklam-modeli', 'WA', 587),
('WA4-09', 'Çalışma ritmi kısa haftalık catch-up ve daha derin sprint toplantılarıyla sıklaştırılacak.', '26 Nisan WA', 'kullanici-kisitlamalari', 'WA', 588),
('WA4-10', 'ODTUGather ile ortak çalışma üzerinden ODTÜ ekosistemine doğrudan erişim stratejik büyüme kanalı olarak görüldü.', '26 Nisan WA', 'influencer-partnerlikleri', 'WA', 589),
('WA4-11', 'Founder 1000 ve yarışmaları başlatmak için ödeme altyapısı kritik ihtiyaç olarak öne çıktı.', '26 Nisan WA', 'audit-kayitlari', 'WA', 590),
('WA4-12', 'Landing page layoutu ışık, renk ve maskot görselleriyle ana sayfaya daha uyumlu hale getirilecek.', '26 Nisan WA', 'mvp-hedefleri', 'WA', 591),
('WA4-13', 'Ömürden Sezgin city-country strategic partner profiline uygun güçlü aday olarak görüşülecek.', '26 Nisan WA', 'influencer-partnerlikleri', 'WA', 592),
('WA4-14', 'RAG sistemi WhatsApp botuna bağlandı ve ana sayfadaki chat akışına entegre edildi.', '27 Nisan WA', 'veritabani-tasarimi', 'WA', 593),
('WA4-15', 'Sosyal medya link paketi standart metin olarak hazırlanıp onepager, WhatsApp ve bot akışlarında kullanılacak.', '27 Nisan WA', 'reklam-modeli', 'WA', 594),
('WA4-16', 'Seren''e ücretli, half-time ve yarım ücret mantığını içeren nihai teklif gönderildi.', '27 Nisan WA', 'ekip-ve-isbirligi', 'WA', 595),
('WA4-17', 'Dış iletişimde Founder unvanı tercih edilecek; Co-founder ifadesi daha zayıf bulundu.', '27 Nisan WA', 'reklam-modeli', 'WA', 596),
('WA4-18', 'Partner yapısı Contributor, 0-30K Influencer, 30-500K Strategic Partner ve 500K+ Community Leader olarak netleştirildi.', '27 Nisan WA', 'influencer-partnerlikleri', 'WA', 597),
('WA4-19', 'Tüm partner kademelerinde gelir anlatısı yaklaşık %20 pay modeliyle sade tutulacak.', '27 Nisan WA', 'reklam-modeli', 'WA', 598),
('WA4-20', 'Hibrit bot hem AI hem kayıt akışıyla WhatsApp ve sayfada canlı çalışır hale geldi.', '27 Nisan WA', 'mvp-hedefleri', 'WA', 599),
('WA4-21', 'Şirket ve Stripe netleşene kadar geçici ödeme sağlayıcısı araştırması sürecek.', '27 Nisan WA', 'audit-kayitlari', 'WA', 600),
('WA4-22', 'Botun kimliği CoreBot adı etrafında ayrıştırılacak; görsel ve isimlendirme daha sonra iyileştirilecek.', '28 Nisan WA', 'mvp-hedefleri', 'WA', 601),
('WA4-23', 'Contributor sayfası sadeleştirilip review sonrası paylaşılacak.', '28 Nisan WA', 'mvp-hedefleri', 'WA', 602),
('WA4-24', 'Ana sınıf yapısı contributor, influencer partner, strategic partner ve community leader olarak tekrar doğrulandı.', '28 Nisan WA', 'influencer-partnerlikleri', 'WA', 603),
('WA4-25', 'Dış partner materyalleri hazır; kurumsal görsel elden geçirme sonraki aşamada yapılacak.', '28 Nisan WA', 'reklam-modeli', 'WA', 604),
('WA4-26', 'WA Bot, Gemini ve benzeri harcamalar muhasebede ayrı kalemler olarak izlenecek.', '28 Nisan WA', 'audit-kayitlari', 'WA', 605),
('WA4-27', 'Contributorlara briefing verildikten sonra kaynak paylaşımını hızlandırmak için ana toplulukla daha entegre çalışmaları planlandı.', '28 Nisan WA', 'topluluk-yonetimi', 'WA', 606),
('WA4-28', 'Contributor dashboardunda referral, bölge, acquisition, görev raporu ve seviye takibi gösterilecek.', '29 Nisan WA', 'veritabani-tasarimi', 'WA', 607),
('WA4-29', 'Duyuru mimarisi sektör bazlı WhatsApp kanal yapısı üzerinden oturtulacak.', '29 Nisan WA', 'topluluk-yonetimi', 'WA', 608),
('WA4-30', 'Contributor dashboardu MVP projesinde açılacak ve demo için MVP ana sayfa basit şifreyle korunacak.', '29 Nisan WA', 'mvp-hedefleri', 'WA', 609),
('WA4-31', 'Ölçeklenme öncesi ayrı bir sunucu kiralanacak.', '29 Nisan WA', 'audit-kayitlari', 'WA', 610),
('WA4-32', 'Tüm partner ve bağlı sitelerden footer ve bağlantı alanları üzerinden karşılıklı backlink toplanacak.', '29 Nisan WA', 'reklam-modeli', 'WA', 611),
('WA4-33', 'Admin influencer verileri şehir, takipçi sayısı ve tema bazında sınıflandırılacak.', '29 Nisan WA', 'veritabani-tasarimi', 'WA', 612),
('WA4-34', 'CorteQS için YouTube kanalı açıldı; ülke-şehir lansman videoları ve influencer videoları burada toplanacak.', '29 Nisan WA', 'reklam-modeli', 'WA', 613),
('WA4-35', 'Tek community yerine kıta bazlı topluluklar ve aralarında kolay geçiş sağlayan bir menü yapısı tercih edilecek.', '29 Nisan WA', 'topluluk-yonetimi', 'WA', 614),
('WA4-36', 'Klasik üyelik formu bot ve RAG akışıyla birlikte pilot olarak korunacak.', '29 Nisan WA', 'mvp-hedefleri', 'WA', 615),
('WA4-37', 'Kullanıcıya platform ROI''sini göstermek için işletme, kuruluş ve danışman hesaplarında retention raporu üretilecek.', '29 Nisan WA', 'audit-kayitlari', 'WA', 616),
('WA4-38', '500K+ segmenti için ayrı Community Leader arşivi açıldı ve büyük influencerlar bu yapıda ayrıştırılacak.', '29 Nisan WA', 'influencer-partnerlikleri', 'WA', 617),
('WA4-39', 'İnsan eklenen gruplar şimdilik ana topluluk dışında tutulacak.', '29 Nisan WA', 'topluluk-yonetimi', 'WA', 618),
('WA4-40', 'Grup kodlamasında 2xx dış gruplar, 1xx iç-paslama grupları için kullanılacak.', '29 Nisan WA', 'veritabani-tasarimi', 'WA', 619),
('WA4-41', 'Founder Sponsor alanı ve Founder Sponsor bilgi sayfası yeni öncelikler olarak belirlendi.', '30 Nisan WA', 'mvp-hedefleri', 'WA', 620),
('WA4-42', 'İşletme ve danışmanlara sosyal medya ve satış dilinde uçtan uca business çözümü mesajı verilecek.', '30 Nisan WA', 'reklam-modeli', 'WA', 621),
('WA4-43', 'Mikro site, website ve uygulama tek dashboarddan yönetilen birleşik teklif yapısı olarak konumlandırılacak.', '30 Nisan WA', 'mvp-hedefleri', 'WA', 622),
('WA4-44', 'Değer önerileri ve subscription yapıları tamamlandı.', '30 Nisan WA', 'mvp-hedefleri', 'WA', 623),
('WA4-45', 'İlk ücretli kategoriler İşletme, Danışman ve Kuruluş olacak; son kullanıcı ile vlogger-blogger şimdilik misafir kalacak.', '30 Nisan WA', 'mvp-hedefleri', 'WA', 624),
('WA4-46', 'CorteQS uçtan uca business operating system olarak konumlandırılacak ve veriler CoreBot''a yüklenecek.', '30 Nisan WA', 'mvp-hedefleri', 'WA', 625),
('WA4-47', 'Kurumsal görünüm AI hissinden çıkarılacak; iletişim tonu movement, güven, aksiyon, bağ ve teknoloji ekseninde kurulacak.', '30 Nisan WA', 'reklam-modeli', 'WA', 626),
('WA4-48', 'Şirketin EIN alması hızlandırılacak.', '30 Nisan WA', 'audit-kayitlari', 'WA', 627),
('WA4-49', 'Stripe aktif olur olmaz paketler, Founding 1000 ve yarışmalar yayına alınacak.', '30 Nisan WA', 'audit-kayitlari', 'WA', 628),
('WA4-50', 'Yarışmalar için diaspora ağı güçlü influencer, sanatçı ve film-edebiyat dünyasından jüri oluşturulacak.', '30 Nisan WA', 'ekip-ve-isbirligi', 'WA', 629),
('WA4-51', 'Contributorları yalnız bırakmamak için tanışma webinarı düzenlenecek.', '30 Nisan WA', 'topluluk-yonetimi', 'WA', 630),
('WA4-52', 'Ödeme altyapısı çözüldüğünde büyük ODTÜ grupları ve derneklerde duyuru dağıtımı yapılacak.', '30 Nisan WA', 'reklam-modeli', 'WA', 631),
('WA4-53', 'Kaş Guide''ın katılımı için topluluğa özel anons hazırlanacak.', '30 Nisan WA', 'topluluk-yonetimi', 'WA', 632),
('WA4-54', 'IT ekibi duyurusu yayımlanmadan önce ayrıca değerlendirilip netleştirilecek.', '30 Nisan WA', 'ekip-ve-isbirligi', 'WA', 633),

-- T9 - 29 Nisan / Strategy & Ops
('T9-01', '29 Nisan toplantısının amacı Cortex için strateji, partnerlikler ve operasyonel sonraki adımları hizalamak olarak belirlendi.', '29 Nisan', 'kullanici-kisitlamalari', 'T9', 650),
('T9-02', 'Founder Partner paketi Qualtron''ın bölgesel danışmanlığını Cortex''in global outreach ve mikro-site, CRM, payment, event araçlarıyla birleştiren upsell modeli olarak tanımlandı.', '29 Nisan', 'reklam-modeli', 'T9', 651),
('T9-03', 'İlk Founder Partner prospecti olarak Hollandalı HR recruiter Serpin için teklif hazırlanacak.', '29 Nisan', 'influencer-partnerlikleri', 'T9', 652),
('T9-04', 'Delaware LLC kurulumu EIN ve Stripe erişimi için kritik yol kalemi olarak önceliklendirildi.', '29 Nisan', 'audit-kayitlari', 'T9', 653),
('T9-05', 'Stripe ve EIN blokajı çözülmeden ücretli servisler ile yarışmalar tam olarak başlatılamayacak.', '29 Nisan', 'audit-kayitlari', 'T9', 654),
('T9-06', '50-50 partnerlik yapısı korunacak; advisor equity partner paylarından %0.5-%2, core team equity ise yaklaşık %2-%3 bandından ayrılacak.', '29 Nisan', 'audit-kayitlari', 'T9', 655),
('T9-07', '29 Ekim''e kadar 50-100 milyon dolar valuation hedefi yatırım çekme anlatısının parçası olarak benimsendi.', '29 Nisan', 'audit-kayitlari', 'T9', 656),
('T9-08', 'Hakan Cengiz Qualtron advisory boarduna mentor ve network erişimi katkısı için dahil edilecek.', '29 Nisan', 'ekip-ve-isbirligi', 'T9', 657),
('T9-09', 'Sena ve Alper Karanlık gibi kilit Alman diaspora networkerlarıyla temas kurulacak.', '29 Nisan', 'influencer-partnerlikleri', 'T9', 658),
('T9-10', 'Contributor dokümanı tamamlandı; prospectlerle paylaşım sürecek ve onboarding webinarı yapılacak.', '29 Nisan', 'topluluk-yonetimi', 'T9', 659),
('T9-11', 'MVP v1 hedef tarihi 29 Ekim olarak korunacak ve full launch öncesi test-bugfix tamponu bırakılacak.', '29 Nisan', 'mvp-hedefleri', 'T9', 660),
('T9-12', 'Ölçeklenmeden önce dedicated Linux servera geçilerek shared host riski proaktif olarak kapatılacak.', '29 Nisan', 'audit-kayitlari', 'T9', 661),
('T9-13', 'WhatsApp stratejisi dağınık grup modelinden tek doğruluk kaynağı olacak daha yapısal bir Channel modeline kayacak.', '29 Nisan', 'topluluk-yonetimi', 'T9', 662),
('T9-14', 'Bot, Channeldan gelen talepleri ekibe köprüleyecek; kanalda doğrudan post atamama sınırı bu şekilde aşılacak.', '29 Nisan', 'veritabani-tasarimi', 'T9', 663),
('T9-15', 'AI botun kimliği CoreBot adıyla ayrıştırılacak.', '29 Nisan', 'mvp-hedefleri', 'T9', 664),
('T9-16', 'WhatsApp API kısıtı nedeniyle botun profil görseli kolay değiştirilemediği için alternatifler araştırılacak.', '29 Nisan', 'mvp-hedefleri', 'T9', 665),
('T9-17', 'Seren''in 20 günlük kurumsal kimlik projesi haftalık video, çoklu platform içerik adaptasyonu ve branding kit deliverablelarıyla ilerleyecek.', '29 Nisan', 'reklam-modeli', 'T9', 666),
('T9-18', 'Tüm partner ve contributorlarla karşılıklı backlink protokolü uygulanacak.', '29 Nisan', 'reklam-modeli', 'T9', 667),
('T9-19', 'Umut yeni Linux serverı kuracak ve diğer projeler için Lovable mikro siteleri hazırlayacak.', '29 Nisan', 'mvp-hedefleri', 'T9', 668),
('T9-20', 'Diğer kullanıcı sınıfları için contributor benzeri dokümanlar üretilecek.', '29 Nisan', 'ekip-ve-isbirligi', 'T9', 669)
on conflict do nothing;
