delete from meeting_notes where source in ('T1', 'T2', 'T3', 'WA', 'NO');

insert into meeting_notes (title, content, date, category, source, sort_order) values

-- T1 — 26 Subat
('T1-01', 'Diaspora WhatsApp gruplarında tekrarlayan sorular ("Hangi doktor?") verimsizlik yaratıyor.', '26 Şubat', 'reklam-modeli', 'T1', 1),
('T1-02', 'Fiziksel etkinlikler düşük kaliteli bağlantılar üretiyor; networking etkin değil.', '26 Şubat', 'reklam-modeli', 'T1', 2),
('T1-03', 'Güvenilir uzman eksikliği dolandırıcılığa açık kapı bırakıyor — ABD $150K dolandırıcılık örneği.', '26 Şubat', 'reklam-modeli', 'T1', 3),
('T1-04', '"Cortex" global platformu: Doğrulanmış Uzman Pazaryeri, vetted profiller ve CTA.', '26 Şubat', 'reklam-modeli', 'T1', 4),
('T1-05', 'AI Twins: ücretli talep üzerine danışmanlık (örn. 20 dk €50).', '26 Şubat', 'mvp-hedefleri', 'T1', 5),
('T1-06', 'Merkezi Etkinlik Yönetimi — biletleme ve kayıt dahil diaspora etkinlikleri hub''ı.', '26 Şubat', 'reklam-modeli', 'T1', 6),
('T1-07', 'WhatsApp ve Telegram gruplarından bilgileri platforma çeken botlar.', '26 Şubat', 'veritabani-tasarimi', 'T1', 7),
('T1-08', 'Barış''ın "101" girişimi (Almanya) + Burak''ın "Cortex" vizyonu global-lokal ortaklık modeli.', '26 Şubat', 'reklam-modeli', 'T1', 8),
('T1-09', '6–8 aylık MVP zaman çizelgesi hedefi.', '26 Şubat', 'mvp-hedefleri', 'T1', 9),
('T1-10', 'Haftalık 1 saatlik Perşembe toplantısı taahhüdü.', '26 Şubat', 'kullanici-kisitlamalari', 'T1', 10),
('T1-11', 'Platform konseptinin tek sayfalık özetini oluşturma.', '26 Şubat', 'reklam-modeli', 'T1', 11),
('T1-12', 'Fuat (Alman politikacı ağı) ile projeyi görüşme planı.', '26 Şubat', 'reklam-modeli', 'T1', 12),

-- T2 — 12 Mart
('T2-01', '"Cortex" ismi "Turkish Atlas"a tercih edildi — evrensel marka, yatırımcı çekiciliği.', '12 Mart', 'mvp-hedefleri', 'T2', 13),
('T2-02', 'Qualtron Sinclair (QS) çatısı altında Cortex, startup portföyü olarak faaliyet görecek.', '12 Mart', 'mvp-hedefleri', 'T2', 14),
('T2-03', 'AI destekli 50+ soru yöntemiyle kapsamlı MVP belgesi oluşturma stratejisi.', '12 Mart', 'veritabani-tasarimi', 'T2', 15),
('T2-04', 'Organik tasarım dili, insan unsurları ve Türk motifleriyle özgün UI/UX yaklaşımı.', '12 Mart', 'veritabani-tasarimi', 'T2', 16),
('T2-05', 'Danışmanlar: profesyonel profil sayfası, 7/24 AI Twin chatbot, ücretli etkinlik yönetimi.', '12 Mart', 'reklam-modeli', 'T2', 17),
('T2-06', 'Kuruluşlar: dernekler, STK''lar, okullar, konsolosluklar — üyelik yönetimi ve bağış işleme.', '12 Mart', 'reklam-modeli', 'T2', 18),
('T2-07', 'İşletmeler: dizin, premium iş ilanı portalı, kupon satışı (Cortex gelir payı), franchise ilanları.', '12 Mart', 'audit-kayitlari', 'T2', 19),
('T2-08', 'WhatsApp/Telegram grupları: merkezi keşif; bot ile onaylı gruplara sponsorlu içerik; reklam geliri payı.', '12 Mart', 'reklam-modeli', 'T2', 20),
('T2-09', 'Etkinlikler: tüm diaspora takvimi + "Öne Çıkan Etkinlik" seçeneği.', '12 Mart', 'reklam-modeli', 'T2', 21),
('T2-10', 'Harita: işletme/kuruluş konumları + vurgulu pin ödemesi.', '12 Mart', 'veritabani-tasarimi', 'T2', 22),
('T2-11', 'Premium abonelikler ve kupon gelir paylaşımı modeli.', '12 Mart', 'audit-kayitlari', 'T2', 23),
('T2-12', 'Dubai Türk İş Konseyi (2000+ işletme) gibi diaspora konseylerinde toplu onboarding.', '12 Mart', 'reklam-modeli', 'T2', 24),
('T2-13', 'Diaspora influencer ortaklıkları ve Ottogether büyüme modeli referans.', '12 Mart', 'reklam-modeli', 'T2', 25),
('T2-14', '17 Mart belge takası ve 19 Mart birleşik plan toplantısı.', '12 Mart', 'kullanici-kisitlamalari', 'T2', 26),
('T2-15', 'Burak: AI destekli MVP belgesi oluştur; Barış: mevcut MVP''yi geliştir.', '12 Mart', 'kullanici-kisitlamalari', 'T2', 27),

-- T3 — 9 Nisan
('T3-01', 'D.Cortex dashboard tek doğruluk kaynağı olacak — tüm notlar, kişiler ve MVP planı tek merkezde.', '9 Nisan', 'veritabani-tasarimi', 'T3', 28),
('T3-02', '"Teknoloji spagettisi" problemi: bilgi WhatsApp, Notion ve Drive arasında dağınık.', '9 Nisan', 'veritabani-tasarimi', 'T3', 29),
('T3-03', 'Versiyonlama: Burak ana Lovable projesine devam; Umut backend ve MVP dışı özellikleri yönetecek.', '9 Nisan', 'veritabani-tasarimi', 'T3', 30),
('T3-04', 'City Partner influencer modeli: Cortex trafik sağlar, partnerler içerik ve yerel bilgi katkısı sunar.', '9 Nisan', 'reklam-modeli', 'T3', 31),
('T3-05', 'İçerik kaynakları: diaspora WhatsApp grupları, YouTube, Instagram, TikTok.', '9 Nisan', 'reklam-modeli', 'T3', 32),
('T3-06', 'Uzun vadeli: içerik havuzundan otomatik seyahat rotası / şehir rehberi üreticisi.', '9 Nisan', 'reklam-modeli', 'T3', 33),
('T3-07', 'Gerilla pazarlama: viral diaspora videoları yorumlarına manuel Cortex linki bırakma.', '9 Nisan', 'reklam-modeli', 'T3', 34),
('T3-08', 'Gönüllü/stajyer ekip modeliyle gerilla pazarlama operasyonunun ölçeklenmesi.', '9 Nisan', 'kullanici-kisitlamalari', 'T3', 35),
('T3-09', 'Cortex.net''i Google Console''a ekleme.', '9 Nisan', 'reklam-modeli', 'T3', 36),
('T3-10', 'Burak''ın 11+ domain''i üzerinden Cortex''e backlink verme.', '9 Nisan', 'reklam-modeli', 'T3', 37),
('T3-11', 'Seren Uzluer''e pazarlama liderliği teklifi — tam zamanlı, hisse bazlı rol.', '9 Nisan', 'kullanici-kisitlamalari', 'T3', 38),
('T3-12', 'SOP dokümanı: hisse, ertelenmiş ücret ve genel çalışma modelini net anlatan onboarding materyali.', '9 Nisan', 'kullanici-kisitlamalari', 'T3', 39),
('T3-13', 'Ekip araçları ve abonelik maliyetleri için tool matrix hazırlanması.', '9 Nisan', 'kullanici-kisitlamalari', 'T3', 40),
('T3-14', 'AI Twin vizyonu: kurucu iletişim, dokümantasyon ve karar süreçlerini otomatikleştirme.', '9 Nisan', 'mvp-hedefleri', 'T3', 41),
('T3-15', '12 Nisan''a kadar D.Cortex paylaşımı ve tool matrix oluşturma.', '9 Nisan', 'kullanici-kisitlamalari', 'T3', 42),

-- WA — 13 Nisan WA
('WA-01', 'LinkedIn üzerinden ilk tanışma — Qatar-Dubai bağlantısı, CorteQS grubu davet linki.', '13 Nisan WA', 'reklam-modeli', 'WA', 43),
('WA-02', 'payaltr.com, qualtronsinclair.com tanıtımı; CORTEX-TURK ana hub fikrinin doğuşu.', '13 Nisan WA', 'reklam-modeli', 'WA', 44),
('WA-03', 'turqua-z.com vs CorteQS — datanın karar vermesi prensibi, marka oylama fikri.', '13 Nisan WA', 'mvp-hedefleri', 'WA', 45),
('WA-04', 'UBT''ye CTO rolünün açıkça teklifi — "CTO sensin".', '13 Nisan WA', 'kullanici-kisitlamalari', 'WA', 46),
('WA-05', 'corteqs.net domain tartışması, isim alternatifleri (TurkAtlas, TurkHub, TurkSphere).', '13 Nisan WA', 'mvp-hedefleri', 'WA', 47),
('WA-06', 'Haftalık Perşembe Zoom serisi başlatıldı: 12:30 QA / 14:30 DE, 108 occurrence.', '13 Nisan WA', 'kullanici-kisitlamalari', 'WA', 48),
('WA-07', 'Lovable workspace admin erişimi, repo GitHub''a push, sandbox/merge stratejisi.', '13 Nisan WA', 'veritabani-tasarimi', 'WA', 49),
('WA-08', 'Blog yazısı planı, Relocation Engine fikri, danışman/yazar kategorisi önerisi.', '13 Nisan WA', 'reklam-modeli', 'WA', 50),
('WA-09', 'Network: Akın Özkan (Mercedes layoff) için iş yerleştirme — Kemal Hakimoğlu referansı.', '13 Nisan WA', 'reklam-modeli', 'WA', 51),
('WA-10', 'delphi.ai incelemesi, RAG (Retrieval-Augmented Generation) ile danışman twin fikri.', '13 Nisan WA', 'mvp-hedefleri', 'WA', 52),
('WA-11', 'cordocu.vercel.app ilk paylaşımı — yeni üyenin mevzuyu hızlı anlayacağı dashboard.', '13 Nisan WA', 'veritabani-tasarimi', 'WA', 53),
('WA-12', 'Tech lead adayı muted observer olarak toplantıya davet edildi.', '13 Nisan WA', 'kullanici-kisitlamalari', 'WA', 54),
('WA-13', 'Cap table modelleri gündeme geldi; "Gönül verecek 10 kişi, sonra para" prensibi.', '13 Nisan WA', 'audit-kayitlari', 'WA', 55),
('WA-14', 'Ortak Instagram collection, danışman/ambassador profil havuzu oluşturma.', '13 Nisan WA', 'reklam-modeli', 'WA', 56),
('WA-15', 'corteqs.net alındı (~226 TL, Doruk üzerinden); corteqs.co ve corteqs.ai planı.', '13 Nisan WA', 'mvp-hedefleri', 'WA', 57),
('WA-16', 'Landing page: ülke kayıt sayaçları, şehir elçisi başvuru sayfası, teaser video.', '13 Nisan WA', 'reklam-modeli', 'WA', 58),
('WA-17', 'Crowdfund açılışı için aynı landing page''in kullanılması fikri.', '13 Nisan WA', 'audit-kayitlari', 'WA', 59),
('WA-18', 'Subdomain mimarisi: Burak Lovable = subdomain, CorDocu = subdomain.', '13 Nisan WA', 'veritabani-tasarimi', 'WA', 60);
