insert into public.meeting_notes (title, content, date, category, source, sort_order) values

-- WA-FULL - 12-24 Nisan ham WhatsApp taramasindan ek karar ve aksiyonlar
('WA-FULL-01', 'WhatsApp danışma hattı onboarding ve SSS yanında insan desteği isteyen kayıtları admin panelde Müşteri Talepleri bölümüne aktaracak.', '12 Nisan WA', 'mvp-hedefleri', 'WA', 500),
('WA-FULL-02', 'CorteQS bot yapısı site içi multilingual bot, kayıtlı kullanıcılara hizmet veren WhatsApp botu ve grup sahiplerine bağlanabilen bot olarak üç kullanım alanında düşünüldü.', '12 Nisan WA', 'mvp-hedefleri', 'WA', 501),
('WA-FULL-03', 'WhatsApp community kurulumu önce numaralar ve admin yapı oturtularak ilerletilecek.', '13 Nisan WA', 'topluluk-yonetimi', 'WA', 502),
('WA-FULL-04', 'Dashboard dosya yapısında AR-GE ve İK klasörleri ayrı tutulacak; CV, görev tanımı, teklif ve kritik araştırmalar bu klasörlerde izlenecek.', '13 Nisan WA', 'veritabani-tasarimi', 'WA', 503),
('WA-FULL-05', 'Salaryinsights.com.tr gibi dış tool fırsatları CorteQS bütçesine kaynak yaratabilecek ayrı yatırım/fırsat havuzu olarak izlenecek.', '15 Nisan WA', 'audit-kayitlari', 'WA', 504),
('WA-FULL-06', 'Cihan değerlendirmesi için Fathom tanışma videosu ve Drive teklif metinleri incelenecek.', '16 Nisan WA', 'ekip-ve-isbirligi', 'WA', 505),
('WA-FULL-07', 'CorteQS sosyal medya şifreleri dashboarda eklenmeden önce güvenlik kontrolünden geçirilecek.', '17 Nisan WA', 'audit-kayitlari', 'WA', 506),
('WA-FULL-08', 'Landing page canlıya açılmadan önce change freeze uygulanacak ve son testler bundan sonra yapılacak.', '18 Nisan WA', 'mvp-hedefleri', 'WA', 507),
('WA-FULL-09', 'Launch haftasında bot hazır olunca sosyal medya postlarıyla early access çağrısı yapılacak ve eş zamanlı LinkedIn job post çıkılacak.', '18 Nisan WA', 'reklam-modeli', 'WA', 508),
('WA-FULL-10', 'Core ve extended ekip ihtiyaçları sosyal medya ve iş ilanı öncesinde netleştirilecek.', '18 Nisan WA', 'ekip-ve-isbirligi', 'WA', 509),
('WA-FULL-11', 'Consultant Board için uluslararası network, yatırım ve know-how katkısı sağlayacak en fazla iki danışman seat değerlendirilecek.', '18 Nisan WA', 'ekip-ve-isbirligi', 'WA', 510),
('WA-FULL-12', 'Consultant Board üyeleri yaklaşık %1 equity bandında değerlendirilecek ve kurumsal görünürlük sağlayan vitrin rolü üstlenecek.', '18 Nisan WA', 'audit-kayitlari', 'WA', 511),
('WA-FULL-13', 'Microsoft Clarity, Google Analytics ve Search Console bağlantıları landing performansını izlemek için kurulacak.', '18 Nisan WA', 'veritabani-tasarimi', 'WA', 512),
('WA-FULL-14', 'CorteQS hesapları için ayrı browser profili kullanılarak sosyal hesaplara ve araçlara geçiş yükü azaltılacak.', '18 Nisan WA', 'kullanici-kisitlamalari', 'WA', 513),
('WA-FULL-15', 'CorteQS domaini açık olan tüm QS/Burak sitelerine backlink olarak eklenecek.', '18 Nisan WA', 'reklam-modeli', 'WA', 514),
('WA-FULL-16', 'Landing page sadeleştirmesi için güvendiği 3-4 kişiden dış geri bildirim alınacak.', '18 Nisan WA', 'mvp-hedefleri', 'WA', 515),
('WA-FULL-17', 'Barış Avustralya görüşmesi Pazartesi Türkiye saatiyle 13:00 olarak planlandı; Cihan görüşmesi aynı gün 15:00 olarak ayrıldı.', '18 Nisan WA', 'kullanici-kisitlamalari', 'WA', 516),
('WA-FULL-18', 'Search Console, Clarity ve Analytics bağlantıları tamamlandıktan sonra SEO/GEO ayarları son incelemeye alınacak.', '18 Nisan WA', 'reklam-modeli', 'WA', 517),
('WA-FULL-19', 'Landing page için AI-first schema, FAQ, video ve uzun açıklama gereksinimleri SEO/GEO uyumu için eklenecek.', '19 Nisan WA', 'reklam-modeli', 'WA', 518),
('WA-FULL-20', 'FAQ listesi için Burak ve sistem ayrı çıktı üretecek, Umut seçip merge edecek.', '19 Nisan WA', 'mvp-hedefleri', 'WA', 519),
('WA-FULL-21', 'WhatsApp topluluğu tek community altında General/Kanal ve kategori bazlı Danışman, Kuruluş, İşletme, City Partner, Vlogger/Blogger ve Bireysel Kullanıcı gruplarıyla kurgulanacak.', '19 Nisan WA', 'topluluk-yonetimi', 'WA', 520),
('WA-FULL-22', 'İç organizasyon yapısı Growth, Marketing, Retention ve AR-GE fonksiyonlarıyla şekillenecek.', '19 Nisan WA', 'ekip-ve-isbirligi', 'WA', 521),
('WA-FULL-23', 'Bot her fonksiyonel birim için ayrı veri evreni yaratacak ve bu veri karar geliştirme süreçlerinde kullanılacak.', '19 Nisan WA', 'veritabani-tasarimi', 'WA', 522),
('WA-FULL-24', 'Ülke bazlı WhatsApp grupları yerine eğitim, sanat ve ihtiyaç temelli gruplar tercih edilecek; ülke/şehir bilgisi portal ve bot tarafında yönetilecek.', '19 Nisan WA', 'topluluk-yonetimi', 'WA', 523),
('WA-FULL-25', 'Instagram içerikleri ve sosyal postlar günlük otomasyonla, örnek olarak her gün 09:00 akışıyla planlanacak.', '19 Nisan WA', 'reklam-modeli', 'WA', 524),
('WA-FULL-26', 'Marketing ekibi Content, Growth, Influencer Management ve Business Development kollarına ayrılacak.', '19 Nisan WA', 'ekip-ve-isbirligi', 'WA', 525),
('WA-FULL-27', 'Turksdiaspora.com, turksdiaspora.net ve turkdiaspora.net domainleri stratejik koruma amacıyla alındı.', '19 Nisan WA', 'audit-kayitlari', 'WA', 526),
('WA-FULL-28', 'Turksdiaspora sosyal medya hesapları alınarak CorteQS büyüme ve savunma stratejisine bağlandı.', '19 Nisan WA', 'reklam-modeli', 'WA', 527),
('WA-FULL-29', 'Veysel Cenk Karakuz Vancouver/Canada sorumlusu adayı olarak kaydedildi.', '19 Nisan WA', 'ekip-ve-isbirligi', 'WA', 528),
('WA-FULL-30', 'Internations benchmark olarak incelenecek ve expat uygulaması karşılaştırma setine alınacak.', '20 Nisan WA', 'mvp-hedefleri', 'WA', 529),
('WA-FULL-31', 'Influencer görüşmelerinden sonra kısa vadeli agile plan çıkarılacak.', '20 Nisan WA', 'kullanici-kisitlamalari', 'WA', 530),
('WA-FULL-32', 'White label modelinde Barış''ın grubu korunup formlar CorteQS üzerinden doldurtularak platformun onun adına açılması seçeneği değerlendirilecek.', '20 Nisan WA', 'reklam-modeli', 'WA', 531),
('WA-FULL-33', 'CorteQS prelaunch akışında kullanıcı önce bot, web kayıt ve WhatsApp topluluğu linkleriyle karşılanacak.', '21 Nisan WA', 'mvp-hedefleri', 'WA', 532),
('WA-FULL-34', 'Influencer lansmanında takipçilerin CorteQS yorumu sonrası otomasyonla referral kodu ve web adresi alması planlandı.', '21 Nisan WA', 'reklam-modeli', 'WA', 533),
('WA-FULL-35', 'Influencer referral kodu WhatsApp hoşgeldin akışına ve kayıt formuna bağlanarak gelir mekanizması başlatılacak.', '21 Nisan WA', 'audit-kayitlari', 'WA', 534),
('WA-FULL-36', 'Landing AI/bot ve klasik form aynı veri yapısına bağlanacak; kullanıcı aynı kaydı üç farklı arayüzden yapabilecek.', '21 Nisan WA', 'mvp-hedefleri', 'WA', 535),
('WA-FULL-37', 'Lovable projelerinde Umut admin yapılacak ve GitHub connection için erişim verilecek.', '21 Nisan WA', 'veritabani-tasarimi', 'WA', 536),
('WA-FULL-38', 'HR profilleri yurt dışı networkleri nedeniyle ikinci influencer segmenti olarak hedeflenecek.', '21 Nisan WA', 'influencer-partnerlikleri', 'WA', 537),
('WA-FULL-39', 'Botun ilk mesajı kullanıcıdan gelirse 24 saat ücretsiz mesajlaşma penceresi kullanılacak.', '21 Nisan WA', 'mvp-hedefleri', 'WA', 538),
('WA-FULL-40', 'Bot canlıya alınmadan önce senaryosu onaylanacak ve 23 Nisan lansmanına kadar oturtulacak.', '21 Nisan WA', 'kullanici-kisitlamalari', 'WA', 539),
('WA-FULL-41', 'Bot topluluğa doğrudan giremeyeceği için kullanıcılar grup açıklaması ve düzenli mesajlarla bota birebir yazmaya yönlendirilecek.', '21 Nisan WA', 'topluluk-yonetimi', 'WA', 540),
('WA-FULL-42', 'Bot numarası güven vermesi için ABD/Dubai yerine Alman numarasıyla değiştirilecek.', '21 Nisan WA', 'mvp-hedefleri', 'WA', 541),
('WA-FULL-43', 'Influencer outreach için isim değiştirilebilir mail, DM ve link template seti hazırlanacak.', '21 Nisan WA', 'influencer-partnerlikleri', 'WA', 542),
('WA-FULL-44', 'Atınç Akçayöz ile hızlı tanışma sonrası teknik ekip mimarisi birlikte tasarlanacak.', '21 Nisan WA', 'ekip-ve-isbirligi', 'WA', 543),
('WA-FULL-45', 'Bot MVP''sinde kayıt dışı uzun cevaplar yerine menüden sayısal seçim yapılacak ve birkaç mesaj sonra site, form veya grup linkine yönlendirme yapılacak.', '21 Nisan WA', 'mvp-hedefleri', 'WA', 544),
('WA-FULL-46', 'Premium üyeler için ileride daha uzun bot cevapları, harita ve gelişmiş danışman yönlendirme özellikleri değerlendirilecek.', '21 Nisan WA', 'reklam-modeli', 'WA', 545),
('WA-FULL-47', 'CorteQS botuna diaspora tarafından ortak kabul görecek ayrı bir isim bulunması için yarışma fikri gündeme geldi.', '21 Nisan WA', 'topluluk-yonetimi', 'WA', 546),
('WA-FULL-48', 'İlk 1000 kullanıcıdan üç ay ücret alınmaması üyelik başlangıç teklifi olarak değerlendirildi.', '21 Nisan WA', 'reklam-modeli', 'WA', 547),
('WA-FULL-49', 'Platform açılana kadar WhatsApp üzerinden hizmet döndürmek için kayıt formlarını RAG''layan daha gelişmiş bot ihtiyacı tanımlandı.', '22 Nisan WA', 'mvp-hedefleri', 'WA', 548),
('WA-FULL-50', 'Instagram otomasyonu düzenli post çıkaracak şekilde kurulacak ve bot talep menüsüyle kullanıcı istekleri toplanacak.', '22 Nisan WA', 'reklam-modeli', 'WA', 549),
('WA-FULL-51', 'Referral kod formatı kaynak, grup, type, tarih ve expire bilgisini taşıyacak; kullanım tarihi kayıt sırasında loglanacak.', '22 Nisan WA', 'veritabani-tasarimi', 'WA', 550),
('WA-FULL-52', 'Referral kodlarının çalınmasını azaltmak için prefix yanında rastgele kuyruk kullanan generator mantığı benimsendi.', '22 Nisan WA', 'audit-kayitlari', 'WA', 551),
('WA-FULL-53', 'Prelaunch için 50-60 potansiyel influencer veya topluluk liderine kısa mail, DM ve onepager ile davet çıkılacak.', '22 Nisan WA', 'influencer-partnerlikleri', 'WA', 552),
('WA-FULL-54', 'AI/tool giderleri için aylık yaklaşık 100-150 EUR teknoloji bütçesi ihtiyacı yazılı olarak not edildi.', '22 Nisan WA', 'audit-kayitlari', 'WA', 553),
('WA-FULL-55', 'ChatGPT Business iki seat ile açılacak, kişisel workspace merge edilmeyecek ve eski sohbetler ayrı tutulacak.', '22 Nisan WA', 'audit-kayitlari', 'WA', 554),
('WA-FULL-56', 'Influencer mail ve DM metinleri Drive Marketing klasöründe tutulacak; gönderimler CorteQS ve QS uzantılı mailden paralel yapılacak.', '22 Nisan WA', 'influencer-partnerlikleri', 'WA', 555),
('WA-FULL-57', 'Admin panelde referral kod source ve type ekleme sistemi geldi; referral raporlama partner/grup bazında izlenecek.', '22 Nisan WA', 'veritabani-tasarimi', 'WA', 556),
('WA-FULL-58', 'Kalıcı WhatsApp bot numarası +491637084577 olarak belirlendi.', '22 Nisan WA', 'mvp-hedefleri', 'WA', 557),
('WA-FULL-59', '23 Nisan''da Almanya101 ve ODTÜ/TED gruplarında prelaunch duyuruları paylaşılacak.', '22 Nisan WA', 'reklam-modeli', 'WA', 558),
('WA-FULL-60', 'Landing formu veya AI formu dolduran kullanıcı WhatsApp''a geldiğinde tekrar form yerine kişiselleştirilmiş hoş geldin akışı görmeli.', '23 Nisan WA', 'mvp-hedefleri', 'WA', 559),
('WA-FULL-61', 'Genel prelaunch referral kodu GGCOLA-PHVTWS olarak üretildi.', '23 Nisan WA', 'audit-kayitlari', 'WA', 560),
('WA-FULL-62', 'Almanya101 WhatsApp prelaunch referral kodu WADELA-KDR8G7 olarak üretildi ve iki ay süreli kullanılacak.', '23 Nisan WA', 'audit-kayitlari', 'WA', 561),
('WA-FULL-63', 'UBT LinkedIn postu için referral kod LIUBLA-RV3S7J olarak üretildi.', '23 Nisan WA', 'audit-kayitlari', 'WA', 562),
('WA-FULL-64', 'Almanya101 topluluğu CorteQS''e katıldı mesajı LinkedIn ve topluluk yöneticilerine gönderilecek.', '23 Nisan WA', 'topluluk-yonetimi', 'WA', 563),
('WA-FULL-65', 'Topluluk liderleri için core topluluktan ayrı davet grubu açıldı ve katılanlara referral gönderilecek.', '23 Nisan WA', 'topluluk-yonetimi', 'WA', 564),
('WA-FULL-66', 'Global topluluk davet metninde kendi yapısı bozulmadan büyüme, gelir motorları ve super-yapıda pozisyon alma mesajı öne çıkarılacak.', '23 Nisan WA', 'topluluk-yonetimi', 'WA', 565),
('WA-FULL-67', 'Cihan''ın ödeme olmadan büyük taahhüde girmeme ihtimali not edildi ve kontrat bazlı çalışma seçeneği değerlendirildi.', '23 Nisan WA', 'ekip-ve-isbirligi', 'WA', 566),
('WA-FULL-68', 'Barış Avustralya''nın çağrıyı gördüğü ama ikna için sözden çok platform hareketi ve kullanıcı kopuşu gerektiği değerlendirildi.', '23 Nisan WA', 'influencer-partnerlikleri', 'WA', 567),
('WA-FULL-69', 'WhatsApp topluluğunda sabah 08:00 ve akşam 20:00 duyuru ritmi değerlendirildi.', '23 Nisan WA', 'topluluk-yonetimi', 'WA', 568),
('WA-FULL-70', 'Duyurularda uzun metin tekrarları yerine pinli ana mesaj, açıklama, sosyal medya post linki ve yeni site güncellemeleri kullanılacak.', '24 Nisan WA', 'topluluk-yonetimi', 'WA', 569),
('WA-FULL-71', 'Landing adminindeki sliding news öğeleri İstatistik, Haber ve Update tipleriyle yönetilecek.', '24 Nisan WA', 'veritabani-tasarimi', 'WA', 570),
('WA-FULL-72', 'Barış Avustralya grubundan export edilen kullanıcılar içinde Avustralya diyenler ayıklanıp Instagramdan takip edilecek.', '24 Nisan WA', 'influencer-partnerlikleri', 'WA', 571),
('WA-FULL-73', 'CorteQS hesabı Barış Avustralya gruplarında konuşmalara katılarak adres görünürlüğü yaratacak.', '24 Nisan WA', 'reklam-modeli', 'WA', 572),
('WA-FULL-74', 'Avustralya influencer listesine invite gönderilmeden önce mevcut tablo ayrıntıları ve CRM alanları netleştirilecek.', '24 Nisan WA', 'veritabani-tasarimi', 'WA', 573)
on conflict do nothing;
