insert into mvp_items (konu, sub, ayrinti, mvp_level, added_by, is_seed) values
('Vizyon & Amaç', NULL, 'Diasporanın dağınık ihtiyaçlarını tek platformda toplamak', 'Atanmadi', 'All', true),
('Vizyon & Amaç', NULL, 'Global Türk rehberi + networking merkezi oluşturmak', 'Atanmadi', 'All', true),
('Vizyon & Amaç', NULL, '"Diaspora için İsviçre çakısı" yaklaşımı', 'Atanmadi', 'All', true),
('Vizyon & Amaç', NULL, 'Tek merkezden bilgi, hizmet ve bağlantı sağlamak', 'Atanmadi', 'All', true),
('Hedef Kitle & Kapsam', NULL, 'Yurtdışında yaşayan tüm Türkler', 'Atanmadi', 'All', true),
('Hedef Kitle & Kapsam', NULL, 'Yeni göç edenler, öğrenciler, profesyoneller', 'Atanmadi', 'All', true),
('Hedef Kitle & Kapsam', NULL, 'İşletme sahipleri, danışmanlar, topluluk yöneticileri', 'Atanmadi', 'All', true),
('Hedef Kitle & Kapsam', NULL, 'Başlangıç ülkeleri: Almanya, UK, UAE, AU, FR, US, CA', 'Atanmadi', 'All', true),
('Temel Problemler', NULL, 'Yerel bilgi eksikliği (doktor, avukat, market vs.)', 'Atanmadi', 'All', true),
('Temel Problemler', NULL, 'Topluluklara erişim zorluğu', 'Atanmadi', 'All', true),
('Temel Problemler', NULL, 'Networking ve iş fırsatlarının görünmemesi', 'Atanmadi', 'All', true),
('Temel Problemler', NULL, 'Diaspora verisinin dağınık olması', 'Atanmadi', 'All', true),
('Kullanıcı Rolleri', NULL, 'Bireysel kullanıcı (görüntüleme, yorum, içerik ekleme)', 'Atanmadi', 'All', true),
('Kullanıcı Rolleri', NULL, 'İşletme sahibi (listing yönetimi, claim)', 'Atanmadi', 'All', true),
('Kullanıcı Rolleri', NULL, 'Topluluk yöneticisi (grup & etkinlik ekleme)', 'Atanmadi', 'All', true),
('Kullanıcı Rolleri', NULL, 'Danışman (KYC ile doğrulama)', 'Atanmadi', 'All', true),
('Kullanıcı Rolleri', NULL, 'Moderatör (onay, spam kontrolü)', 'Atanmadi', 'All', true),
('Auth & Profil Sistemi', NULL, 'Google / Apple login veya auth flow', 'Atanmadi', 'All', true),
('Auth & Profil Sistemi', NULL, 'Kullanıcı tipine göre profil zenginliği', 'Atanmadi', 'All', true),
('Auth & Profil Sistemi', NULL, 'KYC ile doğrulama', 'Atanmadi', 'All', true),
('Auth & Profil Sistemi', NULL, 'Claim sistemi ile işletme sahiplenme', 'Atanmadi', 'All', true),
('Platform Yapısı (Data Model)', NULL, 'Country → City → Category → Listing', 'Atanmadi', 'All', true),
('Platform Yapısı (Data Model)', NULL, 'Çok katmanlı kategori sistemi', 'Atanmadi', 'All', true),
('Platform Yapısı (Data Model)', NULL, 'Geniş listing veri modeli (iletişim, lokasyon, medya vb.)', 'Atanmadi', 'All', true),
('Kategori Yapısı', NULL, 'Sağlık (doktor, dişçi vs.)', 'Atanmadi', 'All', true),
('Kategori Yapısı', NULL, 'Hukuk & danışmanlık', 'Atanmadi', 'All', true),
('Kategori Yapısı', NULL, 'Günlük yaşam (market, kuaför vb.)', 'Atanmadi', 'All', true),
('Kategori Yapısı', NULL, 'Yeme-içme', 'Atanmadi', 'All', true),
('Kategori Yapısı', NULL, 'Eğitim', 'Atanmadi', 'All', true),
('Kategori Yapısı', NULL, 'Hizmetler', 'Atanmadi', 'All', true),
('Kategori Yapısı', NULL, 'İş & kariyer', 'Atanmadi', 'All', true),
('Kategori Yapısı', NULL, 'Topluluklar (WA, Telegram, Discord)', 'Atanmadi', 'All', true),
('Kategori Yapısı', NULL, 'Etkinlikler', 'Atanmadi', 'All', true),
('Arama & AI', NULL, 'Kategori bazlı arama (user, job, kupon, gruplar)', 'Atanmadi', 'All', true),
('Arama & AI', NULL, 'AI destekli doğal dil arama ("Berlin''de Türk dişçi")', 'Atanmadi', 'All', true),
('Arama & AI', NULL, 'Sıralama: ülke, şehir, kategori, featured, sponsored', 'Atanmadi', 'All', true),
('Arama & AI', NULL, 'Veri kaynakları: platform + AI twin + API''ler', 'Atanmadi', 'All', true),
('Harita & Lokasyon', NULL, 'Google Maps entegrasyonu', 'Atanmadi', 'All', true),
('Harita & Lokasyon', NULL, 'Harita üzerinden keşif', 'Atanmadi', 'All', true),
('Harita & Lokasyon', NULL, 'Listing bazlı konum gösterimi', 'Atanmadi', 'All', true),
('İçerik & Veri Yönetimi', NULL, 'Manuel + toplu veri girişi', 'Atanmadi', 'All', true),
('İçerik & Veri Yönetimi', NULL, 'API entegrasyonları (Google Maps, gov.tr)', 'Atanmadi', 'All', true),
('İçerik & Veri Yönetimi', NULL, 'Veri güncelleme planı (henüz net değil)', 'Atanmadi', 'All', true),
('İçerik & Veri Yönetimi', NULL, 'Çok dilli destek (TR, EN, DE)', 'Atanmadi', 'All', true),
('UI/UX', NULL, 'Mobil-first tasarım', 'Atanmadi', 'All', true),
('UI/UX', NULL, '19–24 ekran planı', 'Atanmadi', 'All', true),
('UI/UX', NULL, 'Pastel tonlar + Türk kırmızısı', 'Atanmadi', 'All', true),
('UI/UX', NULL, 'Onboarding: auth + KYC + profil unlock', 'Atanmadi', 'All', true),
('Teknik Altyapı', NULL, 'Tech stack → belirlenmeli', 'Atanmadi', 'All', true),
('Teknik Altyapı', NULL, 'Hosting → belirlenmeli', 'Atanmadi', 'All', true),
('Teknik Altyapı', NULL, 'Database → belirlenmeli', 'Atanmadi', 'All', true),
('Teknik Altyapı', NULL, 'Security & backup → tanımlanmalı', 'Atanmadi', 'All', true),
('Teknik Altyapı', NULL, 'Günlük kapasite hedefi: 100K user', 'Atanmadi', 'All', true),
('AI & Gelecek Özellikler', NULL, 'AI öneri sistemi (henüz net değil)', 'Atanmadi', 'All', true),
('AI & Gelecek Özellikler', NULL, 'AI twin (gelir modeli içinde)', 'Atanmadi', 'All', true),
('AI & Gelecek Özellikler', NULL, 'Akıllı öneri & filtreleme', 'Atanmadi', 'All', true),
('Topluluk & Etkinlik', NULL, 'WhatsApp / Telegram grup listeleri', 'Atanmadi', 'All', true),
('Topluluk & Etkinlik', NULL, 'Grup yönetimi platform dışı', 'Atanmadi', 'All', true),
('Topluluk & Etkinlik', NULL, 'Etkinlik sistemi (konser, meetup, workshop vb.)', 'Atanmadi', 'All', true),
('Topluluk & Etkinlik', NULL, 'Etkinlik detayları: tarih, lokasyon, bilet', 'Atanmadi', 'All', true),
('Yorum & Güven Sistemi', NULL, 'Kullanıcı yorumları ve puanlama', 'Atanmadi', 'All', true),
('Yorum & Güven Sistemi', NULL, 'Google rating entegrasyonu', 'Atanmadi', 'All', true),
('Yorum & Güven Sistemi', NULL, 'Doğrulanmış rozet sistemi', 'Atanmadi', 'All', true),
('Moderasyon', NULL, 'İçerik onayı', 'Atanmadi', 'All', true),
('Moderasyon', NULL, 'Spam filtreleme', 'Atanmadi', 'All', true),
('Moderasyon', NULL, 'Kullanıcı raporlama', 'Atanmadi', 'All', true),
('Moderasyon', NULL, 'Moderatör paneli', 'Atanmadi', 'All', true),
('Pazarlama & Lansman', NULL, 'İlk kanal: Instagram, FB, LinkedIn', 'Atanmadi', 'All', true),
('Pazarlama & Lansman', NULL, 'Beta kullanıcılar: founder network', 'Atanmadi', 'All', true),
('Pazarlama & Lansman', NULL, 'Lansman: 4–6 ay', 'Atanmadi', 'All', true),
('Pazarlama & Lansman', NULL, 'Sosyal medya genişleme planı', 'Atanmadi', 'All', true),
('Gelir Modeli', NULL, 'Üyelik paketleri', 'Atanmadi', 'All', true),
('Gelir Modeli', NULL, 'Reklam & sponsor', 'Atanmadi', 'All', true),
('Gelir Modeli', NULL, 'İş ilanları', 'Atanmadi', 'All', true),
('Gelir Modeli', NULL, 'Kupon satışları', 'Atanmadi', 'All', true),
('Gelir Modeli', NULL, 'Online görüşmeler', 'Atanmadi', 'All', true),
('Gelir Modeli', NULL, 'AI twin hizmetleri', 'Atanmadi', 'All', true),
('Gelir Modeli', NULL, 'Business paketleri (micro site/app)', 'Atanmadi', 'All', true),
('KPI & Başarı Metrikleri', NULL, 'Traction', 'Atanmadi', 'All', true),
('KPI & Başarı Metrikleri', NULL, 'Retention', 'Atanmadi', 'All', true),
('KPI & Başarı Metrikleri', NULL, 'Revenue', 'Atanmadi', 'All', true),
('Hedefler', NULL, '100K kullanıcı', 'Atanmadi', 'All', true),
('Hedefler', NULL, '2000 işletme + danışman', 'Atanmadi', 'All', true),
('Hedefler', NULL, '200K € gelir (ilk yıl)', 'Atanmadi', 'All', true),
('Roadmap', NULL, 'MVP → Web platform', 'Atanmadi', 'All', true),
('Roadmap', NULL, 'V2 → Mobile app', 'Atanmadi', 'All', true),
('Roadmap', NULL, 'Global diaspora expansion', 'Atanmadi', 'All', true),
('Kritik Eksikler / Aksiyonlar', NULL, 'Tech stack seçimi', 'Atanmadi', 'All', true),
('Kritik Eksikler / Aksiyonlar', NULL, 'Hosting & DB kararı', 'Atanmadi', 'All', true),
('Kritik Eksikler / Aksiyonlar', NULL, 'Güvenlik & backup', 'Atanmadi', 'All', true),
('Kritik Eksikler / Aksiyonlar', NULL, 'Analitik araçlar', 'Atanmadi', 'All', true),
('Kritik Eksikler / Aksiyonlar', NULL, 'AI öneri sistemi', 'Atanmadi', 'All', true),
('Kritik Eksikler / Aksiyonlar', NULL, 'Medya storage', 'Atanmadi', 'All', true),
('Kritik Eksikler / Aksiyonlar', NULL, 'Logo / branding', 'Atanmadi', 'All', true);
